'use strict';
const a=id=>document.getElementById(id),accNames=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const ACC_BASS_ROOTS=['B𝄫','F♭','C♭','G♭','D♭','A♭','E♭','B♭','F','C','G','D','A','E','B','F♯','C♯','G♯','D♯','A♯'];
const ACC_ROWS=['counter','bass','major','minor','seventh','diminished'],accRowNames=['Counterbass','Root bass','Major','Minor','Seventh','Diminished'];
const accPC={C:0,F:5,G:7,D:2,A:9,E:4,B:11,'B𝄫':9,'F♭':4,'C♭':11,'G♭':6,'D♭':1,'A♭':8,'E♭':3,'B♭':10,'F♯':6,'C♯':1,'G♯':8,'D♯':3,'A♯':10},accName=m=>accNames[m%12]+(Math.floor(m/12)-1),accLeftLabel=l=>l?`${l.root} ${accRowNames[ACC_ROWS.indexOf(l.row)].toLowerCase()}`:'Rest';
const accLabel=n=>[n.midi!=null?(n.spelling||accName(n.midi)):'',n.left?accLeftLabel(n.left):''].filter(Boolean).join(' + ')||'Rest';
let accCurrent=ACC_LESSONS.find(l=>!Learners.current().progress.accordion.includes(l.id))||ACC_LESSONS[0],accIndex=0,accPlaying=false,accTimer,accAudio,accOsc=[],accPracticed=false,accStage='learn',accView='finger',accScoreNodes=[],accSegments=[],accPreviousPlayed=-1;
Learners.mount();
function renderAccPath(){const done=new Set(Learners.current().progress.accordion);a('accCompleted').textContent=ACC_LESSONS.filter(l=>done.has(l.id)).length;a('accPath').innerHTML=ACC_UNITS.map((name,unit)=>`<section><h3>Unit ${unit+1} · ${name}</h3>${ACC_LESSONS.filter(l=>l.unit===unit).map(l=>`<button data-acc-lesson="${l.id}" class="${l===accCurrent?'selected':''}" aria-current="${l===accCurrent?'step':'false'}"><span>${done.has(l.id)?'✓':ACC_LESSONS.indexOf(l)+1}</span><strong>${l.title}<small>${l.skill}</small></strong></button>`).join('')}</section>`).join('');document.querySelectorAll('[data-acc-lesson]').forEach(b=>b.onclick=()=>chooseAccLesson(b.dataset.accLesson));a('storageWarning').hidden=Learners.storageAvailable;}
function chooseAccLesson(id){const l=ACC_LESSONS.find(l=>l.id===id);if(!l)return;stopAcc();window.speechSynthesis?.cancel();accCurrent=l;accIndex=0;accPracticed=false;a('accUnit').textContent=`BEGINNER · UNIT ${l.unit+1} · ${ACC_UNITS[l.unit].toUpperCase()}`;a('accTitle').textContent=l.title;a('accSkill').textContent=l.skill;a('accTip').textContent=(Learners.current().mode==='young'?'Ask your helper to read and practice with you. ':'')+l.tip;a('accSteps').innerHTML=l.steps.map(s=>`<li>${s}</li>`).join('');a('accReward').hidden=true;renderAccPath();renderAccSequence();showAccNote(l.notes[0]);setAccStage('learn');}
function setAccStage(stage){stopAcc();accStage=stage;for(const name of ['learn','practice','check']){a('acc'+name[0].toUpperCase()+name.slice(1)).hidden=stage!==name;a('acc'+name[0].toUpperCase()+name.slice(1)+'Tab').setAttribute('aria-pressed',String(stage===name));}if(stage==='practice'){if(accView==='sheet')renderAccScore();showAccNote(accCurrent.notes[accIndex]);}if(stage==='check')renderAccCheck();}
function setAccView(view){accView=view;a('accFingerStage').hidden=view!=='finger';a('accSheetStage').hidden=view!=='sheet';a('accFingerTab').setAttribute('aria-pressed',String(view==='finger'));a('accSheetTab').setAttribute('aria-pressed',String(view==='sheet'));if(view==='sheet')renderAccScore();showAccNote(accCurrent.notes[accIndex]);}
function renderAccSequence(){a('accSequence').innerHTML=accCurrent.notes.map((n,i)=>`<button data-acc-index="${i}" aria-label="Event ${i+1}: ${accLabel(n)}"><strong>${accLabel(n)}</strong><small>${n.midi!=null?'R'+n.finger+' ':''}${n.left?'L'+n.left.finger:''} · ${n.beats} beat${n.beats===1?'':'s'}</small></button>`).join('');document.querySelectorAll('[data-acc-index]').forEach(b=>b.onclick=()=>seekAcc(Number(b.dataset.accIndex)));}
function seekAcc(i){stopAcc();accIndex=i;showAccNote(accCurrent.notes[i]);if(a('accSound').checked)ensureAccAudio().then(()=>soundAcc(accCurrent.notes[i]));}
function keySVG(low,high,n,full=false){const whites=[];for(let m=low;m<=high;m++)if(![1,3,6,8,10].includes(m%12))whites.push(m);const width=full?780:620,w=(width-20)/whites.length;let svg='';for(let i=0;i<whites.length;i++){const m=whites[i],active=n.midi===m;svg+=`<rect data-key="${m}" x="${10+i*w}" y="10" width="${w}" height="130" rx="3" fill="${active?'#b84b24':'#fff'}" stroke="#173746"/><text x="${10+(i+.5)*w}" y="120" text-anchor="middle" font-size="${full?14:18}" fill="${active?'white':'#173746'}">${accName(m)}</text>`;if(active)svg+=`<circle cx="${10+(i+.5)*w}" cy="85" r="${full?10:16}" fill="#173746"/><text x="${10+(i+.5)*w}" y="91" text-anchor="middle" font-size="16" fill="white">${n.finger}</text>`;if(m%12===0&&!active)svg+=`<circle cx="${10+(i+.5)*w}" cy="90" r="3" fill="#b84b24"/>`;}
for(let m=low;m<=high;m++)if([1,3,6,8,10].includes(m%12)){const i=whites.indexOf(m-1),active=n.midi===m;if(i<0)continue;const x=10+(i+1)*w;svg+=`<rect data-key="${m}" x="${x-w*.28}" y="10" width="${w*.56}" height="75" rx="3" fill="${active?'#b84b24':'#173746'}"/>`;if(active)svg+=`<text x="${x}" y="65" text-anchor="middle" fill="white" font-size="16">${n.finger}</text>`;}return svg;}
function drawAccKeys(n){const pitches=accCurrent.notes.filter(v=>v.midi!=null).map(v=>v.midi);let low=Math.min(60,...pitches),high=Math.max(67,...pitches);while([1,3,6,8,10].includes(low%12))low--;while([1,3,6,8,10].includes(high%12))high++;a('accKeys').innerHTML=keySVG(low,high,n);a('accFullKeys').innerHTML=keySVG(53,93,n,true);}
function bassSVG(roots,n,full=false){const width=full?1100:650,gap=full?47:75,left=full?125:180;let svg='<text x="10" y="18" font-size="14" fill="#526976">↑ BELLOWS EDGE · flats ← · → sharps</text>';ACC_ROWS.forEach((row,r)=>{const y=55+r*43;svg+=`<text x="8" y="${y+5}" font-size="${full?13:16}" fill="#173746">${accRowNames[r]}</text>`;roots.forEach((root,i)=>{const x=left+i*gap+r*5,active=n.left?.root===root&&n.left?.row===row;svg+=`<circle data-bass="${root}:${row}" cx="${x}" cy="${y}" r="${full?17:21}" fill="${active?'#b84b24':row==='bass'&&root==='C'?'#e7b277':'#fff'}" stroke="#173746" stroke-width="${row==='bass'&&root==='C'?3:1}"/><text x="${x}" y="${y+5}" text-anchor="middle" font-size="${full?12:15}" fill="${active?'white':'#173746'}">${active?n.left.finger:row==='counter'?accNames[((accPC[root]??0)+4)%12]:root}</text>`;});});return svg;}
function showAccNote(n){a('accNow').textContent=accLabel(n);a('accContact').textContent=[n.midi!=null?`Right: ${n.spelling||accName(n.midi)} · finger ${n.finger}${accIndex>0&&accCurrent.notes[accIndex-1].tie?' · keep held through tie':''}`:'Right: rest',n.left?`Left: ${accLeftLabel(n.left)} · finger ${n.left.finger}`:'Left: rest'].join(' | ');drawAccKeys(n);a('accBass').innerHTML=bassSVG(['B♭','F','C','G','D'],n);a('accFullBass').innerHTML=bassSVG(ACC_BASS_ROOTS,n,true);let beat=accCurrent.notes.slice(0,accIndex).reduce((sum,v)=>sum+v.beats,0),out=Math.floor(beat/Number(accCurrent.meter[0])/2)%2===0;a('accBellows').textContent=n.rest?'Pause · release keys · keep counting':out?'← OPEN gently · suggested phrase direction':'→ CLOSE gently · suggested phrase direction';a('accBellows').className='bellows-cue'+(out?'':' push')+(accPlaying?' playing':'');a('accKeys').setAttribute('aria-label',n.midi!=null?`Right hand ${accName(n.midi)}, finger ${n.finger}`:'Right hand resting');a('accBass').setAttribute('aria-label',n.left?`Left hand ${accLeftLabel(n.left)}, finger ${n.left.finger}`:'Left hand resting');document.querySelectorAll('[data-acc-index]').forEach(b=>{const active=Number(b.dataset.accIndex)===accIndex;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});for(const el of accScoreNodes)el.classList.toggle('acc-active',Number(el.dataset.accScoreIndex)===accIndex);a('accPrev').disabled=accIndex===0;a('accNext').disabled=accIndex===accCurrent.notes.length-1;a('accStatus').textContent=`Event ${accIndex+1} of ${accCurrent.notes.length} · ${n.beats} beat${n.beats===1?'':'s'}`;}
function accLeftPitches(l){if(!l)return [];const root=36+accPC[l.root];if(l.row==='bass')return [root];if(l.row==='counter')return [root+4];return (l.row==='major'?[0,4,7]:l.row==='minor'?[0,3,7]:l.row==='seventh'?[0,4,10]:[0,3,9]).map(x=>root+12+x);}
const accABCPitch=m=>{const letter=['C','C','D','D','E','F','F','G','G','A','A','B'][m%12],oct=Math.floor(m/12)-1;return ([1,3,6,8,10].includes(m%12)?'^':'')+(oct>=5?letter.toLowerCase()+"'".repeat(oct-5):letter+','.repeat(Math.max(0,4-oct)));};
const accDuration=b=>b===1?'':Number.isInteger(b)?String(b):b===.5?'/2':b===1.5?'3/2':String(b);
function buildAccScore(lesson,barsPerLine=4){const segments=[],barBeats=Number(lesson.meter[0]);let voices=['',''];for(let voice=0;voice<2;voice++){let beat=0,bar=0;lesson.notes.forEach((n,index)=>{let remaining=n.beats,first=true;while(remaining>0){const duration=Math.min(remaining,barBeats-beat),pitches=voice===0?(n.midi!=null?[n.midi]:[]):accLeftPitches(n.left),label=voice===0?(n.midi!=null?'R'+n.finger:''):(n.left?accLeftLabel(n.left)+' L'+n.left.finger:''),symbol=pitches.length===0?'z':pitches.length===1?voice===0&&n.spelling==='B♭4'?'_B':accABCPitch(pitches[0]):'['+pitches.map(accABCPitch).join('')+']';voices[voice]+=(first&&label?'"^'+label+'"':'')+symbol+accDuration(duration);remaining-=duration;if(pitches.length&&(remaining>0||(voice===0&&n.tie)))voices[voice]+='-';voices[voice]+=' ';if(voice===0)segments.push(index);beat+=duration;first=false;if(beat>=barBeats){voices[voice]+='| ';beat=0;bar++;if(bar%barsPerLine===0)voices[voice]+='\n';}}});voices[voice]=voices[voice].trimEnd().replace(/\|\s*$/,'')+'|]';}
return {abc:`X:1\nT:${lesson.title}\nM:${lesson.meter}\nL:1/4\n%%score { RH LH }\nK:C\nV:RH clef=treble name="Right"\n${voices[0]}\nV:LH clef=bass name="Left"\n${voices[1]}`,segments};}
function renderAccScore(){try{const built=buildAccScore(accCurrent,a('accScore').clientWidth<520?2:4);accSegments=built.segments;ABCJS.renderAbc('accScore',built.abc,{add_classes:true,responsive:'resize',staffwidth:Math.max(280,a('accScore').clientWidth-30),format:{annotationfont:'Arial 11'}});accScoreNodes=[];for(const voice of [0,1]){const els=Array.from(a('accScore').querySelectorAll(`.abcjs-v${voice}.abcjs-note,.abcjs-v${voice}.abcjs-rest`));els.forEach((el,i)=>{const index=accSegments[i];el.dataset.accScoreIndex=index;el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`Event ${index+1}, ${accLabel(accCurrent.notes[index])}`);el.addEventListener('click',()=>seekAcc(index));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();seekAcc(index);}});});accScoreNodes.push(...els);}a('accScoreError').hidden=true;}catch(err){a('accScoreError').hidden=false;a('accScoreError').textContent='Score unavailable. Finger view and playback still work.';console.error(err);}}
async function ensureAccAudio(){if(!accAudio)accAudio=new(window.AudioContext||window.webkitAudioContext)();if(accAudio.state==='suspended')await accAudio.resume();}
function stopAccAudio(){for(const osc of accOsc)try{osc.stop();}catch{}accOsc=[];}
function soundAcc(n,duration=.6,continuation=false){if(!a('accSound').checked||!accAudio)return;const voices=[...(n.midi!=null&&!continuation?[{midi:n.midi,duration}]:[]),...accLeftPitches(n.left).map(midi=>({midi,duration:Math.min(duration,.35)}))];for(const v of voices){const osc=accAudio.createOscillator(),gain=accAudio.createGain(),now=accAudio.currentTime;osc.type='sawtooth';osc.frequency.value=440*Math.pow(2,(v.midi-69)/12);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.045/Math.max(1,voices.length),now+.02);gain.gain.setValueAtTime(.035/Math.max(1,voices.length),now+Math.max(.03,v.duration-.04));gain.gain.linearRampToValueAtTime(0,now+v.duration);osc.connect(gain).connect(accAudio.destination);osc.start();osc.stop(now+v.duration+.02);accOsc.push(osc);osc.onended=()=>{osc.disconnect();gain.disconnect();accOsc=accOsc.filter(o=>o!==osc);};}}
function stopAcc(){clearTimeout(accTimer);accPlaying=false;accPreviousPlayed=-1;stopAccAudio();a('accPlay').textContent='▶ Play along';a('accBellows').classList.remove('playing');}
function accTick(){if(!accPlaying)return;const n=accCurrent.notes[accIndex],duration=n.beats*60/Number(a('accTempo').value);showAccNote(n);let held=duration;for(let j=accIndex;accCurrent.notes[j].tie&&j+1<accCurrent.notes.length;j++)held+=accCurrent.notes[j+1].beats*60/Number(a('accTempo').value);soundAcc(n,held*.97,accIndex>0&&accPreviousPlayed===accIndex-1&&accCurrent.notes[accIndex-1].tie);accPreviousPlayed=accIndex;accTimer=setTimeout(()=>{if(accIndex===accCurrent.notes.length-1){if(a('accLoop').checked)accIndex=0;else{stopAcc();a('accStatus').textContent='Well played. Repeat a phrase or take the quick check.';return;}}else accIndex++;accTick();},duration*1000);}
function renderAccCheck(){a('accReward').hidden=true;a('accFeedback').textContent='';if(!accPracticed){a('accQuestion').textContent='Practice this lesson on your instrument first.';a('accAnswers').innerHTML='<button id="accGoPractice" class="primary">Go to practice →</button>';a('accGoPractice').onclick=()=>setAccStage('practice');return;}const q=accCurrent.check;a('accQuestion').textContent=q.prompt;const options=q.options.map((text,i)=>({text,i}));for(let i=options.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]];}a('accAnswers').innerHTML=options.map(o=>`<button data-acc-answer="${o.i}">${o.text}</button>`).join('');document.querySelectorAll('[data-acc-answer]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.accAnswer)!==q.answer){b.disabled=true;a('accFeedback').textContent='Try again. Revisit the lesson tips if you need a reminder.';return;}const rewarded=Learners.complete('accordion',accCurrent.id);renderAccPath();a('accAnswers').innerHTML='';a('accFeedback').textContent='That’s right.';a('accReward').hidden=false;a('accReward').innerHTML=`<h3>${rewarded?'Well played · +20 XP':'Good review · progress kept'}</h3><p>Only this lesson is marked complete. Earlier lessons stay as you left them.</p><button class="primary" id="accNextLesson">Choose another lesson →</button>`;a('accNextLesson').onclick=()=>chooseAccLesson((ACC_LESSONS[ACC_LESSONS.indexOf(accCurrent)+1]||ACC_LESSONS[0]).id);});}
for(const stage of ['learn','practice','check'])a('acc'+stage[0].toUpperCase()+stage.slice(1)+'Tab').onclick=()=>setAccStage(stage);
a('accStart').onclick=()=>setAccStage('practice');a('accFingerTab').onclick=()=>setAccView('finger');a('accSheetTab').onclick=()=>setAccView('sheet');a('accFinishPractice').onclick=()=>{accPracticed=true;setAccStage('check');};a('accPlay').onclick=async()=>{if(accPlaying){stopAcc();return;}if(a('accSound').checked)await ensureAccAudio();if(accIndex===accCurrent.notes.length-1)accIndex=0;accPlaying=true;a('accPlay').textContent='Ⅱ Pause';accTick();};a('accPrev').onclick=()=>seekAcc(Math.max(0,accIndex-1));a('accNext').onclick=()=>seekAcc(Math.min(accCurrent.notes.length-1,accIndex+1));a('accRestart').onclick=()=>seekAcc(0);a('accTempo').oninput=()=>{a('accTempoValue').textContent=a('accTempo').value+' BPM';stopAcc();};a('accSound').onchange=()=>{if(!a('accSound').checked)stopAccAudio();};document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAcc();});window.addEventListener('resize',()=>{if(accView==='sheet'&&accStage==='practice'){renderAccScore();showAccNote(accCurrent.notes[accIndex]);}});a('accRead').hidden=!window.speechSynthesis;a('accRead').onclick=()=>{window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance([accCurrent.title,accCurrent.tip,...accCurrent.steps].join('. '));speech.rate=Learners.current().mode==='young'?.85:1;window.speechSynthesis.speak(speech);};chooseAccLesson(accCurrent.id);
