'use strict';
const $=id=>document.getElementById(id);
const STRINGS=[{name:'G',midi:55,color:'#2179aa'},{name:'D',midi:62,color:'#b56a10'},{name:'A',midi:69,color:'#16836b'},{name:'E',midi:76,color:'#8156b0'}];
const PATTERN=[{semi:0,finger:0,placement:'Open string'},{semi:1,finger:1,placement:'Low 1st finger'},{semi:2,finger:1,placement:'1st finger'},{semi:3,finger:2,placement:'Low 2nd finger'},{semi:4,finger:2,placement:'High 2nd finger'},{semi:5,finger:3,placement:'3rd finger'},{semi:6,finger:3,placement:'High 3rd finger'},{semi:7,finger:4,placement:'4th finger'}];
const PITCHES=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const note=(s,semi,beats=1)=>({s,semi,beats});
const phrase=(s,arr)=>arr.map(x=>note(s,typeof x==='number'?x:x[0],typeof x==='number'?1:x[1]));
const d=arr=>phrase(1,arr),a=arr=>phrase(2,arr);
const major=s=>[...phrase(s,[0,2,4,5]),...phrase(s+1,[0,2,4,[5,2]]),...phrase(s+1,[4,2,0]),...phrase(s,[5,4,2,[0,2]])];
const twinkle=[...d([0,0]),...a([0,0,2,2,[0,2]]),...d([5,5,4,4,2,2,[0,2]]),...a([0,0]),...d([5,5,4,4,[2,2]]),...a([0,0]),...d([5,5,4,4,[2,2]]),...d([0,0]),...a([0,0,2,2,[0,2]]),...d([5,5,4,4,2,2,[0,2]])];
const ode=d([4,4,5,7,7,5,4,2,0,0,2,4,[4,1.5],[2,.5],[2,2],4,4,5,7,7,5,4,2,0,0,2,4,[2,1.5],[0,.5],[0,2],2,2,4,0,2,[4,.5],[5,.5],4,0,2,[4,.5],[5,.5],4,2,0,2,[7,2],4,4,5,7,7,5,4,2,0,0,2,4,[2,1.5],[0,.5],[0,2]]);
const lessons=[
{id:'open',level:1,title:'Hello, four strings',type:'First sounds',description:'Meet G, D, A, and E. An open string sings with no finger pressing it down.',notes:[0,1,2,3,3,2,1,0].map(s=>note(s,0,2)),steps:['Ask a grown-up or teacher to help tune G3, D4, A4, and E5.','Rest the violin on your left shoulder. Keep your neck and shoulders easy.','Pluck each string first. Then try a slow bow on one string at a time.'],goal:'I can name each string and make a steady sound without squeezing.',tip:'0 means open: lift your fingers clear of the string.'},
{id:'bow',level:1,title:'A gentle bow',type:'Bow & rhythm',description:'Practice steady beats on the D string. Use a relaxed bow hand and move parallel to the bridge.',notes:d([0,0,[0,2],0,0,[0,2],[0,4]]),steps:['Let a teacher help shape your bow hold. Keep your thumb bent and your hand soft.','Bow halfway between bridge and fingerboard. Keep the bow on one string.','Count one beat for short notes and two or four for longer notes. Stop if your hand gets tired.'],goal:'I can bow four gentle, even notes on one string.',tip:'Use a small amount of bow. Listen for a clear sound rather than pressing harder.'},
{id:'first',level:1,title:'Your first finger',type:'First position',description:'Keep your hand near the nut. Place finger 1 on D to make E, then lift it for open D.',notes:d([0,2,0,2,[2,2],[0,2],0,2,[0,2]]),steps:['Finger 1 is your index finger. Your thumb rests lightly beside the neck.','Curve your finger and touch the string with its fingertip.','Place and lift finger 1 slowly. Match the reference pitch by listening.'],goal:'I can move between open D and first-finger E comfortably.',tip:'A violin has no frets. Adjust your fingertip a little until the pitch matches.'},
{id:'three',level:2,title:'Three fingers, four notes',type:'Finger pattern',description:'Play D, E, F♯, and G. High finger 2 sits close to finger 3.',notes:d([0,2,4,[5,2],4,2,[0,2]]),steps:['Play open D, then E with finger 1.','F♯ uses high finger 2. G uses finger 3. The gap between them is small.','Play up and back slowly, keeping your fingers curved.'],goal:'I can play this four-note pattern without rushing.',tip:'F♯ to G is a half step: fingers 2 and 3 sit close together.'},
{id:'hotcross',level:2,title:'Hot Cross Buns',type:'Your first song',description:'A tiny traditional melody using just three notes on the D string.',notes:d([4,2,[0,2],4,2,[0,2],[0,.5],[0,.5],[0,.5],[0,.5],[2,.5],[2,.5],[2,.5],[2,.5],4,2,[0,2]]),steps:['Say “Hot cross buns” with the first three notes.','Tap the short repeated notes on your knee before you bow them.','Try the whole tune slowly. Use Loop to play it again.'],goal:'I can play the tune three times at a comfortable speed.',tip:'The little number underneath each note is its length in beats.'},
{id:'mary',level:2,title:'Mary Had a Little Lamb',type:'Traditional song',description:'A familiar melody to help your fingers find E, F♯, and open D.',notes:d([4,2,0,2,4,4,[4,2],2,2,[2,2],4,7,[7,2],4,2,0,2,4,4,4,4,2,2,4,2,[0,4]]),steps:['Try the first seven notes before the whole song.','The A note uses your pinky, finger 4, on the D string.','Tap a tricky note to hold its diagram still. Practice the phrase again.'],goal:'I can follow the melody and use finger 4 without a tight hand.',tip:'For finger 4, keep the pinky rounded. Open A is an alternative your teacher may choose.'},
{id:'cross',level:3,title:'Across the strings',type:'String crossings',description:'Move from the D string to the A string with a gentle change in bow angle.',notes:[...d([0,2,4,5]),...a([0,2,4,5]),...d([5,4,2,0]),...a([5,4,2,[0,2]])],steps:['Play the D-string pattern first.','At open A, change the bow angle just enough to reach the next string.','Keep your left hand in first position on both strings.'],goal:'I can switch between D and A without catching a third string.',tip:'The highlighted string changes when you cross. Watch the string letter as well as the finger number.'},
{id:'dmajor',level:3,title:'D major, up and down',type:'One-octave scale',description:'A full D-major scale across D and A. It uses F♯ and C♯.',notes:major(1),steps:['Play D–E–F♯–G on the D string.','Continue A–B–C♯–D on the A string.','Return slowly. Listen for the same pitches on the way down.'],goal:'I can play up and down with a steady pulse.',tip:'Use high finger 2 on both D and A for this scale.'},
{id:'twinkle',level:3,title:'Twinkle, Twinkle, Little Star',type:'Traditional song',description:'Put your D and A string skills together in a complete familiar tune.',notes:twinkle,steps:['Learn one line at a time using the note buttons.','Give the longer notes their full two beats.','Try 45 BPM first and increase the speed when it feels easy.'],goal:'I can play the whole tune and keep its rhythm.',tip:'Let your bow change strings smoothly. A small, calm movement is enough.'},
{id:'fourth',level:4,title:'Pinky power',type:'Fourth finger',description:'Play A with finger 4 on D, then compare it with open A. The two notes have the same pitch.',notes:[note(1,7,2),note(2,0,2),...d([5,7,5,4,2,[0,2]]),note(1,7,2),note(2,0,2)],steps:['Listen to open A, then try finger 4 on the D string.','Compare the pitches, moving your fingertip a little if needed.','Keep your wrist easy. Take a break before the pinky gets tired.'],goal:'My fourth-finger A sounds close to open A.',tip:'This lesson deliberately uses two different fingerings for the same pitch.'},
{id:'ode',level:4,title:'Ode to Joy',type:'Beethoven melody',description:'A simplified D-major arrangement of Beethoven’s melody with fourth finger and dotted rhythm.',notes:ode,steps:['Practice the first phrase slowly. Use finger 4 for A.','A 1½-beat note lasts longer than the following ½-beat note.','Use Loop to build a steady rhythm before raising the tempo.'],goal:'I can play the melody with an even pulse and relaxed fourth finger.',tip:'Listen once before playing. The reference is a synthesized practice tone, not a recording of a violin.'},
{id:'lowtwo',level:5,title:'Meet low finger two',type:'New finger pattern',description:'F natural on D sits closer to finger 1. Compare it with F♯ to hear the difference.',notes:d([2,[3,2],2,[4,2],0,2,3,5,3,2,[0,2]]),steps:['Place low finger 2 close to finger 1 for F natural.','Move finger 2 farther toward the bridge for F♯.','Use your ears as well as the diagram. Notice the half-step change.'],goal:'I can show and hear the difference between F and F♯.',tip:'Low 2 and high 2 are two placements of the same finger.'},
{id:'gmajor',level:5,title:'G major colors',type:'One-octave scale',description:'Play G major on the G and D strings. Use high finger 2 on both strings.',notes:[...phrase(0,[0,2,4,5]),...d([0,2,4,[5,2],4,2,0]),...phrase(0,[5,4,2,[0,2]])],steps:['On G, play G–A–B–C with open, 1, high 2, and 3.','On D, play D–E–F♯–G with open, 1, high 2, and 3.','Play back down slowly, listening for the same pitches.'],goal:'I can name the notes in G major and use its F♯.',tip:'G major has one sharp: F♯.'},
{id:'minor',level:5,title:'A minor mood',type:'Natural minor scale',description:'A different sound: A–B–C–D–E–F–G–A. Low fingers 2 and 1 give this scale its color.',notes:[...a([0,2,3,5]),...phrase(3,[0,1,3,[5,2],3,1,0]),...a([5,3,2,[0,2]])],steps:['Use low finger 2 for C on the A string.','Use low finger 1 for F and low finger 2 for G on the E string.','Move slowly between the different finger patterns.'],goal:'I can follow two different finger patterns in one scale.',tip:'F natural on E uses low finger 1, close to the nut.'},
{id:'double',level:6,title:'Two strings together',type:'Double stops',description:'Two notes played together are called a double stop. Begin with open D and A, then try D and F♯.',notes:[{voices:[note(1,0),note(2,0)],beats:4},{voices:[note(1,4),note(2,0)],beats:4},{voices:[note(1,0),note(2,0)],beats:4}],steps:['First find the bow angle that touches open D and A together.','Keep open A ringing while finger 2 makes F♯ on D.','Use gentle pressure. Both notes should sound without squeezing.'],goal:'I can hear both adjacent strings clearly.',tip:'The violin’s curved bridge makes two adjacent strings a good first harmony.'},
{id:'arpeggio',level:6,title:'A chord, one note at a time',type:'D-major arpeggio',description:'Play D–F♯–A–D. These are the notes of a D-major chord, played in sequence.',notes:[...d([0,4]),...a([0,[5,2],0]),...d([4,[0,2]])],steps:['Hold each note while you look at its fingering.','Listen to how D, F♯, and A fit together.','Try the double-stop explorer for two chord tones together.'],goal:'I can play a D-major arpeggio and name its three chord tones.',tip:'Three- and four-string chords are often rolled. This app starts with adjacent two-string shapes.'}
];
const chords=[{name:'D major · F♯ + A',voices:[note(1,4),note(2,0)]},{name:'G major · B + D',voices:[note(0,4),note(1,0)]},{name:'A major · C♯ + E',voices:[note(2,4),note(3,0)]},{name:'A minor · C + E',voices:[note(2,3),note(3,0)]}];
let saved;try{saved=JSON.parse(localStorage.getItem('little-strings-progress')||'[]')}catch{saved=[]}
let completed=new Set(Array.isArray(saved)?saved.filter(id=>lessons.some(l=>l.id===id)):[]),current=lessons[0],index=0,playing=false,timer=null,audio=null,oscillators=[],flipped=false,exploring=false;
const pitch=n=>{let midi=STRINGS[n.s].midi+n.semi;return {midi,name:PITCHES[midi%12],octave:Math.floor(midi/12)-1}};
const voices=n=>n.voices||[n];
const pattern=n=>PATTERN.find(p=>p.semi===n.semi);
const tabLabel=n=>`${STRINGS[n.s].name}:${n.semi}`;
const fingerLabel=n=>{const p=pattern(n);return p.finger===0?'open':`finger ${p.finger}${p.placement.startsWith('Low')?' low':p.placement.startsWith('High')?' high':''}`};
const levels=['First sounds','First melodies','String adventures','Stronger fingers','New colors','Playing in harmony'];
function saveProgress(){try{localStorage.setItem('little-strings-progress',JSON.stringify([...completed]))}catch{$('playStatus').textContent='Progress cannot be saved in this browser. You can still practice.'}}
function renderPath(){ $('lessonList').innerHTML=levels.map((name,i)=>`<div class="level-group"><p>Level ${i+1} · ${name}</p>${lessons.filter(l=>l.level===i+1).map(l=>`<button class="lesson-button ${l===current?'active':''} ${completed.has(l.id)?'done':''}" data-lesson="${l.id}" ${l===current?'aria-current="step"':''}><span class="number">${completed.has(l.id)?'✓':lessons.indexOf(l)+1}</span><span>${l.title}<small>${l.type}</small></span></button>`).join('')}</div>`).join('');$('completedCount').textContent=completed.size;document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>selectLesson(b.dataset.lesson)); }
function selectLesson(id){stop();current=lessons.find(l=>l.id===id);index=0;exploring=false;$('levelLabel').textContent=`LEVEL ${current.level} · ${levels[current.level-1].toUpperCase()}`;$('lessonTitle').textContent=current.title;$('lessonBadge').textContent=current.type;$('lessonDescription').textContent=current.description;$('steps').innerHTML=current.steps.map(s=>`<li>${s}</li>`).join('');$('goal').textContent=current.goal;updateComplete();renderPath();renderSequence();scoreDirty=true;if(practiceView==='sheet')renderScore();showNote(current.notes[0]);$('playStatus').textContent='Tap any note to see its fingering.';}
function updateComplete(){$('complete').textContent=completed.has(current.id)?'Practiced ✓ · tap to undo':'I practiced this lesson ✓'}
function renderSequence(){ $('sequence').innerHTML=current.notes.map((n,i)=>`<button data-index="${i}" aria-label="Note ${i+1}: ${voices(n).map(v=>`${pitch(v).name}, tab ${tabLabel(v)}, ${fingerLabel(v)}`).join(' and ')}, ${n.beats} beats">${voices(n).map(v=>pitch(v).name).join('+')}<strong class="tab-label">${voices(n).map(tabLabel).join(' + ')}</strong><small>${voices(n).map(fingerLabel).join(' + ')}</small><small>${n.beats} beat${n.beats===1?'':'s'}</small></button>`).join('');document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{stop();exploring=false;index=Number(b.dataset.index);showNote(current.notes[index]);ensureAudio().then(()=>playTone(current.notes[index]));});}
function fingerboard(n){const vs=voices(n),xs=flipped?[270,210,150,90]:[90,150,210,270];const y=semi=>80+(1-Math.pow(2,-semi/12))*910;
let svg=`<defs><linearGradient id="board" x2="1" y2="0"><stop stop-color="#202932"/><stop offset=".5" stop-color="#38424b"/><stop offset="1" stop-color="#202932"/></linearGradient></defs><path d="M72 80 L288 80 L309 465 L51 465Z" fill="url(#board)"/><rect x="70" y="74" width="220" height="10" rx="3" fill="#ddd4be"/><text x="320" y="85" font-size="12" fill="#536775">nut</text>`;
[2,3,4,5,7].forEach(semi=>svg+=`<line x1="60" x2="300" y1="${y(semi)}" y2="${y(semi)}" stroke="#ffffff" stroke-opacity=".7" stroke-width="2.625" stroke-dasharray="6 5"/>`);
svg+='<line x1="60" x2="300" y1="440" y2="440" stroke="#ffffff" stroke-opacity=".7" stroke-width="2.625" stroke-dasharray="6 5"/>';
STRINGS.forEach((s,i)=>{let active=vs.some(v=>v.s===i);svg+=`<text x="${xs[i]}" y="45" text-anchor="middle" font-size="21" font-weight="700" fill="${s.color}">${s.name}</text><line x1="${xs[i]}" x2="${xs[i]}" y1="82" y2="437" stroke="${active?s.color:'#c0c8cb'}" stroke-width="${active?5:3-i*.5}"/>`;PATTERN.filter(p=>p.semi>0).forEach(p=>svg+=`<circle cx="${xs[i]}" cy="${y(p.semi)}" r="5" fill="#ffffff"/>`);});
vs.forEach(v=>{let p=pattern(v),cy=p.finger===0?62:y(v.semi);svg+=`<circle class="marker" cx="${xs[v.s]}" cy="${cy}" r="21" fill="${STRINGS[v.s].color}" stroke="white" stroke-width="3"/><text x="${xs[v.s]}" y="${cy+6}" text-anchor="middle" font-size="19" font-weight="700" fill="white">${p.finger}</text>`});$('fingerboard').innerHTML=svg;$('fingerboard').setAttribute('aria-label',vs.map(v=>`${pitch(v).name}${pitch(v).octave}, ${STRINGS[v.s].name} string, ${pattern(v).placement}`).join('; '));}
function drawStaff(n){let svg='';for(let i=0;i<5;i++)svg+=`<line x1="18" x2="220" y1="${25+i*10}" y2="${25+i*10}" stroke="#9eaeb7"/>`;svg+='<text x="20" y="63" font-size="44" fill="#173746">𝄞</text>';
voices(n).forEach((v,i)=>{let p=pitch(v),degree={C:0,D:1,E:2,F:3,G:4,A:5,B:6}[p.name[0]]+p.octave*7,cy=65-(degree-30)*5,cx=110+i*32;for(let ly=75;ly<=cy;ly+=10)svg+=`<line x1="${cx-13}" x2="${cx+13}" y1="${ly}" y2="${ly}" stroke="#173746"/>`;for(let ly=15;ly>=cy;ly-=10)svg+=`<line x1="${cx-13}" x2="${cx+13}" y1="${ly}" y2="${ly}" stroke="#173746"/>`;svg+=`<ellipse cx="${cx}" cy="${cy}" rx="8" ry="5" transform="rotate(-20 ${cx} ${cy})" fill="${STRINGS[v.s].color}"/><line x1="${cx+7}" x2="${cx+7}" y1="${cy}" y2="${cy-26}" stroke="#173746"/>`;if(p.name.includes('♯'))svg+=`<text x="${cx-23}" y="${cy+5}" font-size="19">♯</text>`});$('staff').innerHTML=`<svg viewBox="0 -10 240 105" role="img" aria-label="Pitch reference in treble clef; rhythms appear in the note buttons">${svg}</svg>`;}
function showNote(n){fingerboard(n);drawStaff(n);updateScore(n);$('noteName').innerHTML=voices(n).map(v=>{let p=pitch(v);return `${p.name}<sub>${p.octave}</sub>`}).join(' + ');$('noteInstruction').innerHTML=voices(n).map(v=>`<div class="note-instruction">${STRINGS[v.s].name} string · ${pattern(v).placement}</div>`).join('');$('fingerKey').innerHTML=voices(n).map(v=>`<span class="finger-pill"><strong>Tab ${tabLabel(v)}</strong> · ${pattern(v).finger===0?'0 · no fingers':`${pattern(v).finger} · ${['','index','middle','ring','pinky'][pattern(v).finger]}`}</span>`).join('');$('technique').textContent=exploring?'Keep your thumb light and your fingers curved. Use your ears to fine-tune the pitch.':current.tip;document.querySelectorAll('[data-index]').forEach(b=>{let active=!exploring&&Number(b.dataset.index)===index;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('previous').disabled=!exploring&&index===0;$('next').disabled=!exploring&&index===current.notes.length-1;}
function stopAudio(){oscillators.forEach(o=>{try{o.stop()}catch{}});oscillators=[];}
async function ensureAudio(){if(!$('sound').checked)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')await audio.resume()}catch{$('playStatus').textContent='Audio is unavailable here. The visual lesson still works.'}}
function playTone(n,duration=.7){if(!$('sound').checked||!audio||audio.state!=='running')return;stopAudio();voices(n).forEach(v=>{let o=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;o.type='triangle';o.frequency.value=440*Math.pow(2,(pitch(v).midi-69)/12);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.14/voices(n).length,now+.03);gain.gain.setValueAtTime(.14/voices(n).length,now+Math.max(.04,duration-.07));gain.gain.linearRampToValueAtTime(0,now+duration);o.connect(gain).connect(audio.destination);o.start(now);o.stop(now+duration);oscillators.push(o);});}
function stop(){playing=false;clearTimeout(timer);timer=null;stopAudio();$('play').textContent='▶ Play along';}
function tick(){if(!playing)return;let n=current.notes[index],duration=n.beats*60/Number($('tempo').value);showNote(n);playTone(n,Math.max(.1,duration*.9));$('playStatus').textContent=`Note ${index+1} of ${current.notes.length} · ${n.beats} beat${n.beats===1?'':'s'}`;timer=setTimeout(()=>{if(!playing)return;if(index===current.notes.length-1){if($('loop').checked)index=0;else{stop();$('playStatus').textContent='Well played! Try it again, or mark this lesson practiced.';return;}}else index++;tick()},duration*1000);}
$('play').onclick=async()=>{if(playing){stop();return}await ensureAudio();if(exploring||index===current.notes.length-1)index=0;exploring=false;playing=true;$('play').textContent='Ⅱ Pause';tick()};
$('previous').onclick=()=>{stop();exploring=false;index=Math.max(0,index-1);showNote(current.notes[index])};$('next').onclick=()=>{stop();exploring=false;index=Math.min(current.notes.length-1,index+1);showNote(current.notes[index])};$('restart').onclick=()=>{stop();exploring=false;index=0;showNote(current.notes[index]);$('playStatus').textContent='Back to the first note.'};
$('tempo').oninput=()=>{$('tempoValue').textContent=`${$('tempo').value} BPM`;if(playing){clearTimeout(timer);stopAudio();tick()}};
$('sound').onchange=async()=>{$('sound').checked?await ensureAudio():stopAudio()};
$('mirror').onclick=()=>{flipped=!flipped;$('mirror').setAttribute('aria-pressed',String(flipped));fingerboard(displayedNote);};
let displayedNote=current.notes[0];const originalShow=showNote;showNote=function(n){displayedNote=n;originalShow(n)};
$('complete').onclick=()=>{completed.has(current.id)?completed.delete(current.id):completed.add(current.id);saveProgress();updateComplete();renderPath()};
$('progressButton').onclick=()=>{$('progressDetail').textContent=`${completed.size} of ${lessons.length} lessons practiced. ${completed.size===lessons.length?'You have explored every lesson!':'Take your time and revisit your favorites.'}`;$('resetMessage').textContent='';$('resetProgress').textContent='Reset progress';$('progressDialog').showModal()};$('closeDialog').onclick=()=>$('progressDialog').close();
let resetArmed=false;$('resetProgress').onclick=()=>{if(!resetArmed){resetArmed=true;$('resetProgress').textContent='Confirm reset';$('resetMessage').textContent='This clears all practiced lessons on this device. Tap Confirm reset to continue.';return}completed.clear();saveProgress();renderPath();updateComplete();$('progressDetail').textContent=`0 of ${lessons.length} lessons practiced.`;$('resetMessage').textContent='Progress reset. You can start fresh.';$('resetProgress').textContent='Reset progress';resetArmed=false};$('progressDialog').addEventListener('close',()=>resetArmed=false);
function explore(n){stop();exploring=true;showNote(n);ensureAudio().then(()=>playTone(n));$('playStatus').textContent='Explorer view · Play along returns to your lesson.';$('fingerboard').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})}
function renderExplorer(mode){$('notesTab').classList.toggle('selected',mode==='notes');$('chordsTab').classList.toggle('selected',mode==='chords');if(mode==='notes'){$('noteExplorer').innerHTML=STRINGS.map((s,i)=>`<div class="note-row"><strong>${s.name} string</strong>${PATTERN.map(p=>`<button data-string="${i}" data-semi="${p.semi}" aria-label="${pitch(note(i,p.semi)).name}, ${p.placement}">${pitch(note(i,p.semi)).name}<strong class="tab-label">${tabLabel(note(i,p.semi))}</strong><small>${fingerLabel(note(i,p.semi))}</small></button>`).join('')}</div>`).join('');document.querySelectorAll('[data-string]').forEach(b=>b.onclick=()=>explore(note(Number(b.dataset.string),Number(b.dataset.semi))))}else{$('noteExplorer').innerHTML='<p class="small">These are two-note parts of a chord. Bow both highlighted adjacent strings together.</p>'+chords.map((c,i)=>`<div class="note-row"><button data-chord="${i}">${c.name}<strong class="tab-label">${c.voices.map(tabLabel).join(' + ')}</strong><small>${c.voices.map(fingerLabel).join(' + ')}</small></button></div>`).join('');document.querySelectorAll('[data-chord]').forEach(b=>b.onclick=()=>explore(chords[Number(b.dataset.chord)]))}}
$('notesTab').onclick=()=>renderExplorer('notes');$('chordsTab').onclick=()=>renderExplorer('chords');document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});


let practiceView='finger',scoreDirty=true,scoreSegments=[],scoreKey='',scoreNodes=[];
function abcPitch(n,accidentals){const p=pitch(n),letter=p.name[0],oct=p.octave;let abc=oct>=5?letter.toLowerCase():letter;abc+=oct>5?"'".repeat(oct-5):oct<4?','.repeat(4-oct):'';const key=letter+oct,sharp=p.name.includes('♯'),previous=accidentals.get(key)||false;let prefix=sharp===previous?'':sharp?'^':'=';accidentals.set(key,sharp);return prefix+abc;}
function abcDuration(beats){return beats===1?'':Number.isInteger(beats)?String(beats):`${Math.round(beats*2)}/2`;}
function buildScore(notes,title,barsPerLine){let abc=`X:1\nT:${title}\nM:4/4\nL:1/4\nK:C clef=treble\n`,beat=0,bar=0,accidentals=new Map(),segments=[];notes.forEach((n,sourceIndex)=>{let remaining=n.beats||1,first=true;while(remaining>0){const duration=Math.min(remaining,4-beat),tones=voices(n).map(v=>abcPitch(v,accidentals)),symbol=tones.length===1?tones[0]:`[${tones.join('')}]`,label=voices(n).map(v=>`${tabLabel(v)} · ${fingerLabel(v)}`).join(' + '),start=abc.length;abc+=(first?`"^${label}"`:'')+symbol+abcDuration(duration);remaining-=duration;if(remaining>0)abc+='-';segments.push({sourceIndex,start,end:abc.length,duration});abc+=' ';first=false;beat+=duration;if(beat>=4){abc+='| ';beat=0;bar++;accidentals.clear();if(bar%barsPerLine===0)abc+='\n';}}});abc=abc.trimEnd();if(beat===0)abc=abc.replace(/\|\s*$/,'');abc+='|]';return {abc,segments};}
function renderScore(n=displayedNote){if(practiceView!=='sheet')return;const notes=exploring?[{...n,beats:n.beats||1}]:current.notes;const title=exploring?'Note practice':current.title;const key=exploring?JSON.stringify(notes):current.id;const width=Math.max(280,$('fullScore').clientWidth||600),barsPerLine=width<520?2:4;scoreKey=key;scoreDirty=false;$('scoreTitle').textContent=title;scoreNodes=[];if(!window.ABCJS){$('scoreError').hidden=false;$('scoreError').textContent='Sheet music could not load. Finger view and playback are still available.';return;}
try{const built=buildScore(notes,title,barsPerLine);scoreSegments=built.segments;window.ABCJS.renderAbc('fullScore',built.abc,{add_classes:true,responsive:'resize',staffwidth:width-25,paddingtop:12,paddingbottom:20,paddingleft:10,paddingright:10,scale:1,format:{titlefont:'Georgia 20',annotationfont:'Arial 11'},selectTypes:false,clickListener:(elem)=>{const segment=scoreSegments.find(s=>elem.startChar>=s.start&&elem.startChar<s.end);if(!segment||exploring)return;stop();index=segment.sourceIndex;showNote(current.notes[index]);ensureAudio().then(()=>playTone(current.notes[index]));$('playStatus').textContent=`Note ${index+1} of ${current.notes.length} · tap Play along to continue.`;}});
scoreNodes=Array.from($('fullScore').querySelectorAll('.abcjs-note'));scoreNodes.forEach((el,i)=>{const segment=scoreSegments[i];if(!segment)return;el.dataset.scoreIndex=segment.sourceIndex;el.setAttribute('role','button');el.setAttribute('tabindex','0');const note=notes[segment.sourceIndex];el.setAttribute('aria-label',`Note ${segment.sourceIndex+1}: ${voices(note).map(v=>`${pitch(v).name}${pitch(v).octave}, ${tabLabel(v)}, ${fingerLabel(v)}`).join(' and ')}`);el.addEventListener('click',()=>{if(exploring)return;stop();index=segment.sourceIndex;showNote(current.notes[index]);ensureAudio().then(()=>playTone(current.notes[index]));$('playStatus').textContent=`Note ${index+1} of ${current.notes.length} · tap Play along to continue.`;});el.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&!exploring){event.preventDefault();stop();index=segment.sourceIndex;showNote(current.notes[index]);ensureAudio().then(()=>playTone(current.notes[index]));}});});$('scoreError').hidden=true;}catch(error){$('fullScore').textContent='';$('scoreError').hidden=false;$('scoreError').textContent='This score could not be drawn. Please use Finger view.';console.error(error);}}
function updateScore(n){if(practiceView!=='sheet')return;const key=exploring?JSON.stringify([{...n,beats:n.beats||1}]):current.id;if(scoreDirty||key!==scoreKey)renderScore(n);const currentIndex=exploring?0:index;scoreNodes.forEach(el=>{const active=Number(el.dataset.scoreIndex)===currentIndex;el.classList.toggle('score-active',active);el.setAttribute('aria-pressed',String(active));});$('scoreCurrent').textContent=voices(n).map(v=>`${pitch(v).name}${pitch(v).octave} · ${tabLabel(v)} · ${fingerLabel(v)}`).join(' + ');}
function setPracticeView(view){practiceView=view;$('fingerStage').hidden=view!=='finger';$('sheetStage').hidden=view!=='sheet';$('fingerView').classList.toggle('selected',view==='finger');$('sheetView').classList.toggle('selected',view==='sheet');$('fingerView').setAttribute('aria-pressed',String(view==='finger'));$('sheetView').setAttribute('aria-pressed',String(view==='sheet'));if(view==='sheet'){renderScore();updateScore(displayedNote);}}
$('fingerView').onclick=()=>setPracticeView('finger');$('sheetView').onclick=()=>setPracticeView('sheet');
let scoreResizeTimer;window.addEventListener('resize',()=>{clearTimeout(scoreResizeTimer);scoreResizeTimer=setTimeout(()=>{scoreDirty=true;if(practiceView==='sheet'){renderScore();updateScore(displayedNote);}},150);});
selectLesson('open');renderExplorer('notes');
