'use strict';
const en=id=>document.getElementById(id);
let ensembleSong=ENSEMBLE_SONGS[0],ensembleSteps=buildEnsemble(ensembleSong),ensembleIndex=0,ensemblePart='violin',ensemblePlaying=false,ensembleTimer=null,ensembleAudio=null,ensembleNodes=[],ensembleSources=[],ensembleLastBeat=-1;
const ensembleEnabled={violin:true,ukulele:true,accordion:true};
function ensembleABCNote(midi){let name=(ensembleSong.key==='Cm'?['=C','^C','=D','_E','=E','=F','^F','=G','_A','=A','_B','=B']:['C','^C','D','^D','E','F','^F','G','^G','A','^A','B'])[midi%12],oct=Math.floor(midi/12)-1;if(oct>=5)name=name.toLowerCase();return name+(oct>5?"'".repeat(oct-5):oct<4?','.repeat(4-oct):'');}
function ensemblePitches(part,instrument){if(part.rest)return [];if(part.chord)return ENSEMBLE_CHORDS[part.chord].frets.map((f,s)=>[67,60,64,69][s]+f);if(instrument==='bass'){const left=part.bass||part.left;if(!left)return [];const chord=ENSEMBLE_CHORDS[left.chord||(left.root==='G'?'G7':left.root)];return left.type==='bass'?[chord.root-12]:chord.tones.map(p=>p-12);}return [part.midi];}
function ensembleLabel(part,instrument){if(instrument==='bass'){const left=part.bass||part.left;return left?`${left.root} ${left.type} · ${left.finger}`:'';}if(part.rest)return '';if(instrument==='violin')return `${['G','D','A','E'][part.s]}:${part.semi}`;if(instrument==='ukulele')return part.chord?`${part.chord} · strum ↓`:`${['G','C','E','A'][part.s]}:${part.fret}`;return `RH ${part.finger}`;}
function buildEnsembleScore(song,steps,barsPerLine=2){
 const beats=Number(song.meter.split('/')[0]);let abc=`X:1\nT:${song.title}\nM:${song.meter}\nL:1/4\nQ:1/4=${song.tempo}\n%%score V1 V2 { V3 V4 }\nV:V1 clef=treble name="Violin"\nV:V2 clef=treble name="Ukulele"\nV:V3 clef=treble name="Accordion RH"\nV:V4 clef=bass name="Accordion bass"\nK:${song.key||'C'}\n`,segments=[];
 for(const [voice,instrument] of [['V1','violin'],['V2','ukulele'],['V3','accordion'],['V4','bass']]){
  abc+=`[V:${voice}] `;
  steps.forEach((step,i)=>{const part=step.parts[instrument==='bass'?'accordion':instrument],pitches=ensemblePitches(part,instrument),start=abc.length,label=ensembleLabel(part,instrument),symbol=pitches.length===0?'z':pitches.length===1?ensembleABCNote(pitches[0]):'['+pitches.map(ensembleABCNote).join('')+']';abc+=(label?`"^${label}"`:'')+symbol+(step.beats===1?'':`${step.beats*8}/8`)+(instrument==='bass'?part.bassTie?'-':'':part.tie?'-':'');segments.push({start,end:abc.length,step:i,instrument});abc+=' ';if((step.beat+step.beats)%beats===0){abc+='| ';if((step.beat+step.beats)%(beats*barsPerLine)===0)abc+='\n';}});abc=abc.trimEnd().replace(/\|\s*$/,'');abc+='|]\n';
 }
 return {abc,segments};
}
function renderEnsembleScore(){
 try{const built=buildEnsembleScore(ensembleSong,ensembleSteps,en('ensembleScore').clientWidth>600?4:2);let mapped=[];
 window.ABCJS.renderAbc('ensembleScore',built.abc,{responsive:'resize',staffwidth:Math.max(260,en('ensembleScore').clientWidth-30),add_classes:true,selectTypes:['note'],clickListener:elem=>{const s=built.segments.find(s=>elem.startChar<s.end&&elem.endChar>s.start);if(s)seekEnsemble(s.step);}});
 // ABCJS arranges voices by system; use parsed source offsets rather than DOM order.
 const tune=window.ABCJS.parseOnly(built.abc)[0];for(const line of tune.lines)for(const staff of line.staff||[])for(const voice of staff.voices||[])for(const event of voice)if(event.el_type==='note'){const s=built.segments.find(s=>event.startChar<s.end&&event.endChar>s.start);mapped.push(s);}
 ensembleNodes=Array.from(en('ensembleScore').querySelectorAll('.abcjs-note,.abcjs-rest'));ensembleNodes.forEach((node,i)=>{const segment=mapped[i];if(!segment)return;node.dataset.ensembleBeat=segment.step;node.setAttribute('role','button');node.setAttribute('tabindex','0');node.setAttribute('aria-label',`${segment.instrument}, bar ${ensembleSteps[segment.step].bar}, beat ${ensembleSteps[segment.step].beat%Number(ensembleSong.meter.split('/')[0])+1}`);node.onclick=()=>seekEnsemble(segment.step);node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();seekEnsemble(segment.step);}};});en('ensembleScoreError').hidden=true;
 }catch(error){en('ensembleScoreError').hidden=false;en('ensembleScoreError').textContent='Sheet music could not load. Finger guides and playback remain available.';console.error(error);}
}
function ensembleSVG(body,box,label){return `<svg viewBox="${box}" role="img" aria-label="${label}">${body}</svg>`;}
function ensembleDiagram(part,instrument){
 if(instrument==='violin'){
  const xs=semi=>100+(1-Math.pow(2,-semi/12))*1450;let svg='<path d="M92 42H680V194H92Z" fill="#303c46"/><rect x="86" y="40" width="9" height="158" fill="#ddd4be"/>';
  for(let semi=1;semi<=7;semi++)svg+=`<line x1="${xs(semi)}" x2="${xs(semi)}" y1="43" y2="195" stroke="white" stroke-width="2.625" stroke-opacity=".35" stroke-dasharray="6 5"/>`;
  ['G','D','A','E'].forEach((name,s)=>{const y=65+s*36;svg+=`<text x="35" y="${y+5}" fill="#173746">${name}</text><line x1="93" x2="680" y1="${y}" y2="${y}" stroke="${!part.rest&&part.s===s?'#b84b24':'#b8c4cb'}" stroke-width="3"/>`;});
  if(!part.rest)svg+=`<circle cx="${part.semi===0?75:xs(part.semi)}" cy="${65+part.s*36}" r="16" fill="#b84b24"/><text x="${part.semi===0?75:xs(part.semi)}" y="${71+part.s*36}" fill="white" text-anchor="middle">${part.finger}</text>`;
  return ensembleSVG(svg,'0 0 720 220','Violin first-position contact; nut on the left');
 }
 if(instrument==='ukulele'){
  let svg='<rect x="100" y="30" width="550" height="155" rx="5" fill="#71503a"/><rect x="96" y="28" width="8" height="160" fill="#ddd4be"/>';
  for(let f=1;f<=5;f++)svg+=`<line x1="${100+f*100}" x2="${100+f*100}" y1="30" y2="185" stroke="#c4c4c4" stroke-width="3"/><text x="${100+f*100}" y="210" text-anchor="middle">${f}</text>`;
  ['G','C','E','A'].forEach((name,s)=>{const y=52+s*36;svg+=`<text x="25" y="${y+5}">${name}</text><line x1="100" x2="650" y1="${y}" y2="${y}" stroke="#eee1c7" stroke-width="2"/>`;const chord=part.chord&&ENSEMBLE_CHORDS[part.chord],active=!part.rest&&(chord||part.s===s);if(active){const fret=chord?chord.frets[s]:part.fret,finger=chord?chord.fingers[s]:part.finger,x=fret===0?75:100+fret*100-25;svg+=`<circle cx="${x}" cy="${y}" r="16" fill="#16836b"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="white">${finger}</text>`;}});return ensembleSVG(svg,'0 0 700 225','Ukulele fret contacts; finger numbers in the circles');
 }
 part={...part,left:part.bass||part.left};let svg='';const keys=part.midi<60?[53,55,57,59,60]:[60,62,64,65,67];keys.forEach((m,i)=>{const x=25+i*70;svg+=`<rect x="${x}" y="30" width="68" height="135" fill="${part.midi===m?'#e7b277':'white'}" stroke="#173746"/><text x="${x+34}" y="147" text-anchor="middle">${ensemblePitch(m)}</text>`;if(part.midi===m)svg+=`<circle cx="${x+34}" cy="105" r="18" fill="#b84b24"/><text x="${x+34}" y="111" text-anchor="middle" fill="white">${part.finger}</text>`;});(part.midi<60?[0,1,2]:[0,1,3]).forEach(i=>svg+=`<rect x="${76+i*70}" y="30" width="29" height="65" fill="${part.midi===58&&i===2?'#b84b24':'#173746'}"/>`);if(part.midi===58)svg+='<text x="230" y="75" fill="white" text-anchor="middle">1</text>';
 svg+='<text x="435" y="20">Bellows edge ↑ · bass window</text>';
 ['counterbass','bass','major','minor','seventh','diminished'].forEach((row,r)=>{svg+=`<text x="385" y="${48+r*30}" font-size="12">${row}</text>`;['Bb','F','C','G'].forEach((root,c)=>{const active=part.left&&part.left.root===root&&part.left.type===row,cx=480+c*45,cy=44+r*30;svg+=`<circle cx="${cx}" cy="${cy}" r="13" fill="${active?'#b84b24':'#dae4e9'}" stroke="#173746"/><text x="${cx}" y="${cy+4}" font-size="12" text-anchor="middle" fill="${active?'white':'#173746'}">${active?part.left.finger:root}</text>`;});});return ensembleSVG(svg,'0 0 660 235','Accordion right hand and Bb F C G Stradella buttons');
}
function showEnsemble(){
 const step=ensembleSteps[ensembleIndex],part=step.parts[ensemblePart],name=ENSEMBLE_NAMES[ensemblePart];
 en('ensemblePartTitle').textContent=name+(ensembleSong.lead===ensemblePart?' · featured melody':' · accompaniment');
 en('ensembleContact').textContent=part.rest?'Rest · listen and count':ensemblePart==='ukulele'&&part.chord?`${part.chord} chord · gentle down strum`:ensemblePart==='violin'?`${ensemblePitch(part.midi)} · ${ensembleLabel(part,'violin')} · finger ${part.finger}${part.continue?' · keep the bow moving':''}`:ensemblePart==='ukulele'?`${ensemblePitch(part.midi)} · ${ensembleLabel(part,'ukulele')} · finger ${part.finger}${part.continue?' · let it ring':' · pluck'}`:`${ensemblePitch(part.midi)} · right finger ${part.finger}${part.left?` · left ${part.left.root} ${part.left.type}, finger ${part.left.finger}`:' · left hand rests'}`;
 en('ensembleDiagram').innerHTML=ensembleDiagram(part,ensemblePart);en('ensemblePartTip').textContent={violin:'First position. 0 means open. C and F use low second finger where appropriate; the dashed lines are pitch guides, not physical frets.',ukulele:'Standard high-G tuning. Press just behind the fret; 0 means open. Pluck the melody softly. Chord diagrams show finger numbers.',accordion:'Follow the highlighted right-hand key; reposition between held backing notes. Left bass uses finger 4, chords finger 3. The marked C button must be verified on your instrument. Use gentle bellows and change direction between phrases.'}[ensemblePart];
 ensembleNodes.forEach(node=>node.classList.toggle('ensemble-active',Number(node.dataset.ensembleBeat)===ensembleIndex));en('ensemblePrevious').disabled=ensembleIndex===0;en('ensembleNext').disabled=ensembleIndex===ensembleSteps.length-1;
 document.querySelectorAll('[data-ensemble-step]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.ensembleStep)===ensembleIndex);b.setAttribute('aria-pressed',String(Number(b.dataset.ensembleStep)===ensembleIndex));});
 en('ensembleStatus').textContent=`Bar ${step.bar} of ${Math.ceil((ensembleSteps.at(-1).beat+ensembleSteps.at(-1).beats)/Number(ensembleSong.meter.split('/')[0]))} · beat ${step.beat%Number(ensembleSong.meter.split('/')[0])+1} · ${step.chord}`;
}
function stopEnsemble(){clearTimeout(ensembleTimer);ensemblePlaying=false;ensembleLastBeat=-1;en('ensemblePlay').textContent='▶ Play trio';ensembleSources.forEach(o=>{try{o.stop();}catch{}});ensembleSources=[];}
function seekEnsemble(i){stopEnsemble();ensembleIndex=Math.max(0,Math.min(ensembleSteps.length-1,i));showEnsemble();}
function ensembleTone(midi,duration,instrument,level=1){if(!ensembleAudio||ensembleAudio.state!=='running')return;const o=ensembleAudio.createOscillator(),g=ensembleAudio.createGain(),now=ensembleAudio.currentTime;o.type={violin:'triangle',ukulele:'sine',accordion:'triangle',click:'sine'}[instrument];o.frequency.value=440*2**((midi-69)/12);const volume=(instrument==='click'?.06:instrument==='ukulele'?.12:.055)*level;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(volume,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(ensembleAudio.destination);o.start();o.stop(now+duration);ensembleSources.push(o);o.onended=()=>{ensembleSources=ensembleSources.filter(s=>s!==o);o.disconnect();g.disconnect();};}
function tickEnsemble(){if(!ensemblePlaying)return;showEnsemble();const step=ensembleSteps[ensembleIndex],seconds=60/Number(en('ensembleTempo').value);
 for(const instrument of ENSEMBLE_INSTRUMENTS){if(!ensembleEnabled[instrument])continue;const part=step.parts[instrument],pitches=ensemblePitches(part,instrument),gain=ensembleSong.lead===instrument?1.5:.3;if(!part.continue||ensembleLastBeat!==ensembleIndex-1){let length=step.beats;for(let i=ensembleIndex;ensembleSteps[i].parts[instrument].tie&&i+1<ensembleSteps.length;i++)length+=ensembleSteps[i+1].beats;for(const p of pitches)ensembleTone(p,seconds*length*.95,instrument,gain/Math.sqrt(pitches.length||1));}if(instrument==='accordion'&&(!part.bassContinue||ensembleLastBeat!==ensembleIndex-1)){let length=step.beats;for(let i=ensembleIndex;ensembleSteps[i].parts.accordion.bassTie&&i+1<ensembleSteps.length;i++)length+=ensembleSteps[i+1].beats;for(const p of ensemblePitches(part,'bass'))ensembleTone(p,seconds*length*.8,'accordion',.15);}}
 ensembleLastBeat=ensembleIndex;ensembleTimer=setTimeout(()=>{if(ensembleIndex+1<ensembleSteps.length){ensembleIndex++;tickEnsemble();}else if(en('ensembleLoop').checked){ensembleIndex=0;tickEnsemble();}else{stopEnsemble();en('ensembleStatus').textContent='Together to the finish! Swap parts or practice again.';}},seconds*step.beats*1000);
}
async function playEnsemble(){if(ensemblePlaying){stopEnsemble();return;}const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext){en('ensembleStatus').textContent='Audio is unavailable in this browser. Tap the beats to follow the parts.';return;}ensembleAudio??=new AudioContext();await ensembleAudio.resume();if(ensembleIndex===ensembleSteps.length-1)ensembleIndex=0;ensemblePlaying=true;en('ensemblePlay').textContent='Ⅱ Pause';const beats=Number(ensembleSong.meter.split('/')[0]);let count=0;function countIn(){if(!ensemblePlaying)return;if(count===beats){tickEnsemble();return;}en('ensembleStatus').textContent=`Count in · ${++count} of ${beats}`;ensembleTone(count===1?84:79,.08,'click');ensembleTimer=setTimeout(countIn,60000/Number(en('ensembleTempo').value));}countIn();}
function renderEnsembleSongs(){en('ensembleSongs').innerHTML=ENSEMBLE_INSTRUMENTS.map(i=>`<h3>${ENSEMBLE_NAMES[i]} leads</h3>`+ENSEMBLE_SONGS.filter(s=>s.lead===i).map(s=>`<button class="ensemble-song" data-ensemble-song="${s.id}" aria-current="${s===ensembleSong}">${s.title}<small>${Learners.current().progress.ensemble.includes(s.id)?'✓ Practiced · ':''}${s.difficulty||'Beginner'} · ${s.meter} · ${s.tempo} BPM</small></button>`).join('')).join('');document.querySelectorAll('[data-ensemble-song]').forEach(b=>b.onclick=()=>chooseEnsemble(b.dataset.ensembleSong));en('ensembleComplete').disabled=Learners.current().progress.ensemble.includes(ensembleSong.id);en('ensembleComplete').textContent=en('ensembleComplete').disabled?'Practiced ✓':'We practiced this arrangement ✓';}
function chooseEnsemble(id){const song=ENSEMBLE_SONGS.find(s=>s.id===id);if(!song)return;stopEnsemble();ensembleSong=song;ensembleSteps=buildEnsemble(song);ensembleIndex=0;ensemblePart=song.lead;en('ensembleTitle').textContent=song.title;en('ensembleLead').textContent=ENSEMBLE_NAMES[song.lead].toUpperCase()+' TAKES THE MELODY';en('ensembleCredit').textContent=song.credit;en('ensembleSources').replaceChildren(...(song.sources||[]).map(source=>{const a=document.createElement('a');a.href=source.url;a.textContent=source.name;a.target='_blank';a.rel='noopener';a.style.marginRight='1rem';return a;}));en('ensembleTempo').value=song.tempo;en('ensembleTempoValue').textContent=song.tempo+' BPM';en('ensembleSequence').innerHTML=ensembleSteps.map((s,i)=>`<button data-ensemble-step="${i}" aria-label="Bar ${s.bar}, beat ${s.beat%Number(song.meter.split('/')[0])+1}">${s.bar}:${s.beat%Number(song.meter.split('/')[0])+1}</button>`).join('');document.querySelectorAll('[data-ensemble-step]').forEach(b=>b.onclick=()=>seekEnsemble(Number(b.dataset.ensembleStep)));renderEnsembleSongs();renderEnsemblePartTabs();renderEnsembleScore();showEnsemble();}
function renderEnsemblePartTabs(){en('ensemblePartTabs').innerHTML=ENSEMBLE_INSTRUMENTS.map(i=>`<button data-ensemble-part="${i}" aria-pressed="${i===ensemblePart}" class="${i===ensemblePart?'selected':''}">${ENSEMBLE_NAMES[i]} part</button>`).join('');document.querySelectorAll('[data-ensemble-part]').forEach(b=>b.onclick=()=>{ensemblePart=b.dataset.ensemblePart;renderEnsemblePartTabs();showEnsemble();});}
function renderEnsembleMixer(){en('ensembleMixer').innerHTML=ENSEMBLE_INSTRUMENTS.map(i=>`<div><label><input type="checkbox" data-ensemble-mute="${i}" ${ensembleEnabled[i]?'checked':''}> ${ENSEMBLE_NAMES[i]}</label><button data-ensemble-solo="${i}">Hear only ${ENSEMBLE_NAMES[i]}</button></div>`).join('')+'<button id="ensembleAll">Hear full trio</button>';document.querySelectorAll('[data-ensemble-mute]').forEach(b=>b.onchange=()=>{stopEnsemble();ensembleEnabled[b.dataset.ensembleMute]=b.checked;});document.querySelectorAll('[data-ensemble-solo]').forEach(b=>b.onclick=()=>{stopEnsemble();for(const i of ENSEMBLE_INSTRUMENTS)ensembleEnabled[i]=i===b.dataset.ensembleSolo;renderEnsembleMixer();});en('ensembleAll').onclick=()=>{stopEnsemble();for(const i of ENSEMBLE_INSTRUMENTS)ensembleEnabled[i]=true;renderEnsembleMixer();};}
Learners.mount();en('ensemblePlay').onclick=playEnsemble;en('ensemblePrevious').onclick=()=>seekEnsemble(ensembleIndex-1);en('ensembleNext').onclick=()=>seekEnsemble(ensembleIndex+1);en('ensembleRestart').onclick=()=>seekEnsemble(0);en('ensemblePrint').onclick=()=>window.print();en('ensembleTempo').oninput=()=>{stopEnsemble();en('ensembleTempoValue').textContent=en('ensembleTempo').value+' BPM';};en('ensembleComplete').onclick=()=>{Learners.complete('ensemble',ensembleSong.id);renderEnsembleSongs();};let ensembleResize;window.addEventListener('resize',()=>{clearTimeout(ensembleResize);ensembleResize=setTimeout(()=>{renderEnsembleScore();showEnsemble();},150);});window.addEventListener('pagehide',stopEnsemble);renderEnsembleMixer();chooseEnsemble(new URLSearchParams(location.search).get('song')||ENSEMBLE_SONGS[0].id);
