'use strict';
// Song resources are linked; these playable sequences are original accompaniment drills, not song transcriptions.
const FORMBY_SONGS=[
 {id:'formby-lamp',title:'Leaning on a Lamp Post',focus:'Smooth chord changes',chords:['C','Am','F','G7','C','F','G7','C'],source:'https://www.gotaukulele.com/2011/12/leaning-on-lamppost-ukulele-chords.html',sourceLabel:'Open song chords'},
 {id:'formby-windows',title:'When I’m Cleaning Windows',focus:'Light, even upstrokes',chords:['C','G7','C','F','C','G7','C','C'],source:'https://www.ukulele-tabs.com/uke-songs/George%2BFormby/when-im-cleaning-windows-uke-tab-23736.html',sourceLabel:'Open song chords'},
 {id:'formby-nice',title:'It’s Turned Out Nice Again',focus:'A steady performance pulse',chords:['C','F','G7','C','Am','F','G7','C'],source:'https://www.traditionalmusic.co.uk/formby-song-book/its_turned_out_nice_again-1939c.htm',sourceLabel:'Free song chart / PDF'},
 {id:'formby-banjo',title:'With My Little Ukulele in My Hand',focus:'Short, bouncy chord attacks',chords:['C','Am','C','G7','F','C','G7','C'],source:'https://www.guitartabsexplorer.com/formby-george/with-my-little-ukulele-in-my-hand-chords',sourceLabel:'Free song chord chart'},
 {id:'formby-races',title:'Riding in the TT Races',focus:'Relaxed rhythm at a faster pulse',chords:['C','F','C','G7','C','F','G7','C'],source:'https://forum.ukuleleunderground.com/threads/riding-in-the-t-t-races.10569/',sourceLabel:'Community song chord chart'},
 {id:'formby-fanny',title:'Fanlight Fanny',focus:'Clean returns to the home chord',chords:['C','G7','Am','F','C','F','G7','C'],source:'https://www.traditionalmusic.co.uk/formby-song-book/fanlight_fanny-1935c.htm',sourceLabel:'Free song chart / PDF'}
];
UKE_UNITS.push({title:'George Formby room',description:'Songs and original preparation drills.'});
const FORMBY_LESSONS=FORMBY_SONGS.map(song=>({id:song.id,title:song.title+' · preparation',unit:UKE_UNITS.length-1,skill:'Secret room · original accompaniment drill',secret:true,tip:'This playable drill builds coordination for your Formby practice. It is an original exercise, not the song’s melody or exact chord chart. Open the linked song resource for the actual arrangement.',young:'Practice the short drill with a helper first. Ask your helper to choose a suitable song and read any external words with you.',adult:'A separate accompaniment warm-up for the linked repertoire. Standard G–C–E–A tuning; adapt from any resource in another tuning.',steps:['Hold each displayed chord with the fingers shown.','For each beat, brush down on the number, then up on “and”. Keep the wrist loose.','Slow the drill down until the chord changes feel easy. Use the linked chart separately to learn the song.'],notes:song.chords.flatMap(name=>[ukeChord(name,.5,'down'),ukeChord(name,.5,'up'),ukeChord(name,.5,'down'),ukeChord(name,.5,'up'),ukeChord(name,.5,'down'),ukeChord(name,.5,'up'),ukeChord(name,.5,'down'),ukeChord(name,.5,'up')]),checks:[]}));
