'use strict';
// Device-local profiles shared by all instruments. No personal account or network requests.
window.Learners=(()=>{
 const KEY='little-strings-learners-v1';let state,storageAvailable=true;
 const fresh=()=>({version:1,active:'first',profiles:[{id:'first',name:'My practice',mode:'older',goal:1,progress:{violin:[],ukulele:[],accordion:[]},awarded:{violin:[],ukulele:[],accordion:[]},days:{},xp:0}]});
 try{state=JSON.parse(localStorage.getItem(KEY)||'null');if(!state||state.version!==1||!Array.isArray(state.profiles)||!state.profiles.length)state=fresh();}catch{state=fresh();}
 const valid=p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&['young','older','adult'].includes(p.mode)&&[1,2,3].includes(p.goal)&&p.progress&&Array.isArray(p.progress.violin)&&Array.isArray(p.progress.ukulele)&&p.days&&typeof p.days==='object'&&Number.isFinite(p.xp);
 state.profiles=state.profiles.filter(valid);for(const p of state.profiles){p.awarded=p.awarded&&Array.isArray(p.awarded.violin)&&Array.isArray(p.awarded.ukulele)?p.awarded:{violin:p.progress.violin.slice(),ukulele:p.progress.ukulele.slice()};p.progress.accordion=Array.isArray(p.progress.accordion)?p.progress.accordion:[];p.awarded.accordion=Array.isArray(p.awarded.accordion)?p.awarded.accordion:p.progress.accordion.slice();}if(!state.profiles.length)state=fresh();if(!state.profiles.some(p=>p.id===state.active))state.active=state.profiles[0].id;
 function write(){try{localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;}return storageAvailable;}
 let existing=false;try{existing=!!localStorage.getItem(KEY);}catch{storageAvailable=false;}
 if(!existing){try{const old=JSON.parse(localStorage.getItem('little-strings-progress')||'[]');if(Array.isArray(old))state.profiles[0].progress.violin=old.filter(v=>typeof v==='string');state.profiles[0].awarded.violin=state.profiles[0].progress.violin.slice();}catch{}write();}
 function current(){return state.profiles.find(p=>p.id===state.active);}
 function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
 function complete(instrument,id){const p=current();if(!p.progress[instrument].includes(id)){p.progress[instrument].push(id);p.awarded??={violin:[],ukulele:[]};const rewarded=!p.awarded[instrument].includes(id);if(rewarded){p.awarded[instrument].push(id);p.xp+=20;p.days[today()]=(p.days[today()]||0)+1;}write();window.dispatchEvent(new Event('learnerprogress'));return rewarded;}return false;}
 function setProgress(instrument,ids){const p=current();const old=p.progress[instrument].slice();for(const id of ids)if(!old.includes(id))complete(instrument,id);p.progress[instrument]=[...new Set(ids)];write();window.dispatchEvent(new Event('learnerprogress'));}
 function streak(){const days=current().days,d=new Date();if(!days[today()])d.setDate(d.getDate()-1);let n=0;while(n<10000){const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(!days[k])break;n++;d.setDate(d.getDate()-1);}return n;}
 function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 function summary(){const p=current();return `${p.xp} XP · ${streak()} day${streak()===1?'':'s'} · ${p.days[today()]||0}/${p.goal} today`;}
 function mount(){let target=document.querySelector('[data-learner-control]');if(!target){target=document.createElement('div');target.className='learner-control';document.querySelector('header')?.append(target);}if(!target)return;
  target.innerHTML=`<button id="learnerOpen" class="learner-button" type="button">${escape(current().name)} <span>▾</span></button><small id="learnerStats">${summary()}</small>`;
  if(!document.getElementById('learnerDialog')){const dlg=document.createElement('dialog');dlg.id='learnerDialog';dlg.className='learner-dialog';dlg.innerHTML=`<button type="button" id="learnerClose" class="dialog-close" aria-label="Close profiles">×</button><h2>Who’s practicing?</h2><p>Separate paths for everyone. Saved on this device.</p><div id="learnerList"></div><form id="learnerForm"><h3>Add a learner</h3><label>Nickname<input id="learnerName" maxlength="30" required autocomplete="off" placeholder="A name you like"></label><label>Lesson style<select id="learnerMode"><option value="young">Young learner · with a helper</option><option value="older" selected>Older learner · independent</option><option value="adult">Adult · concise guidance</option></select></label><label>Daily goal<select id="learnerGoal"><option value="1">1 lesson · a gentle start</option><option value="2">2 lessons · steady practice</option><option value="3">3 lessons · extra practice</option></select></label><button class="primary" type="submit">Create learner</button></form><p id="learnerMessage" role="status"></p><div class="backup-tools"><button type="button" id="learnerExport">Export progress</button><label class="file-button">Import progress<input type="file" id="learnerImport" accept="application/json,.json"></label></div><p class="small">No sign-in. Export a backup to move progress to another device. Profiles are not private accounts.</p>`;document.body.append(dlg);
   document.getElementById('learnerClose').onclick=()=>dlg.close();
   document.getElementById('learnerForm').onsubmit=e=>{e.preventDefault();const name=document.getElementById('learnerName').value.trim();if(!name)return;const p={id:crypto.randomUUID(),name,mode:document.getElementById('learnerMode').value,goal:Number(document.getElementById('learnerGoal').value),progress:{violin:[],ukulele:[],accordion:[]},awarded:{violin:[],ukulele:[],accordion:[]},days:{},xp:0};state.profiles.push(p);state.active=p.id;write();dlg.close();location.reload();};
   document.getElementById('learnerExport').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='little-strings-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
   document.getElementById('learnerImport').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1024*1024)throw Error('This file is too large.');const incoming=JSON.parse(await file.text());if(incoming.version!==1||!Array.isArray(incoming.profiles)||!incoming.profiles.length||!incoming.profiles.every(valid))throw Error('Choose a Little Strings progress export.');for(const p of incoming.profiles){const clean={id:crypto.randomUUID(),name:p.name.slice(0,30),mode:p.mode,goal:p.goal,progress:{violin:p.progress.violin.filter(v=>typeof v==='string'),ukulele:p.progress.ukulele.filter(v=>typeof v==='string'),accordion:(p.progress.accordion||[]).filter(v=>typeof v==='string')},awarded:{violin:(p.awarded?.violin||p.progress.violin).filter(v=>typeof v==='string'),ukulele:(p.awarded?.ukulele||p.progress.ukulele).filter(v=>typeof v==='string'),accordion:(p.awarded?.accordion||p.progress.accordion||[]).filter(v=>typeof v==='string')},days:Object.fromEntries(Object.entries(p.days).filter(([k,v])=>/^\d{4}-\d{2}-\d{2}$/.test(k)&&Number.isInteger(v)&&v>=0)),xp:Math.max(0,p.xp)};state.profiles.push(clean);}write();renderList();document.getElementById('learnerMessage').textContent='Imported as additional profiles. Existing learners are kept.';}catch(err){document.getElementById('learnerMessage').textContent=err.message;}e.target.value='';};
  }
  document.getElementById('learnerOpen').onclick=()=>{renderList();document.getElementById('learnerDialog').showModal();};document.body.dataset.learnerMode=current().mode;
 }
 function renderList(){document.getElementById('learnerList').innerHTML=state.profiles.map(p=>`<button type="button" data-profile="${escape(p.id)}" class="profile-option ${p.id===state.active?'selected':''}"><strong>${escape(p.name)}</strong><span>${p.mode==='young'?'With a helper':p.mode==='adult'?'Adult':'Independent'} · ${p.xp} XP ${p.id===state.active?'· current':''}</span></button>`).join('');document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{state.active=b.dataset.profile;write();location.reload();});}
 window.addEventListener('storage',event=>{if(event.key===KEY)location.reload();});
 window.addEventListener('learnerprogress',()=>{const s=document.getElementById('learnerStats');if(s)s.textContent=summary();const warning=document.getElementById('storageWarning');if(warning)warning.hidden=storageAvailable;});
 return {current,complete,setProgress,streak,today,summary,mount,escape,get storageAvailable(){return storageAvailable;}};
})();
