'use strict';
const u=id=>document.getElementById(id),ukeNames=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const ukePitch=v=>UKE_STRINGS[v.s].midi+v.fret;
const ukeVoices=n=>n.rest?[]:n.chord?UKE_CHORDS[n.chord].frets.map((fret,s)=>({s,fret,finger:UKE_CHORDS[n.chord].fingers[s]})):[n];
const ukeName=n=>n.rest?'Rest':n.chord?({'C-high':'C · upper','D-high':'D · upper'}[n.chord]||n.chord):ukeNames[ukePitch(n)%12];
const ukeTab=n=>n.rest?'—':n.chord?UKE_CHORDS[n.chord].frets.join('–'):`${UKE_STRINGS[n.s].name}:${n.fret}`;
let ukeDone=new Set(Learners.current().progress.ukulele.filter(id=>UKE_LESSONS.some(l=>l.id===id))),ukeCurrent=UKE_LESSONS.find(l=>!ukeDone.has(l.id))||UKE_LESSONS[0],ukeIndex=0,ukePlaying=false,ukeTimer=null,ukeAudio=null,ukeOscillators=[],ukeFlip=false,ukeStage='learn',ukeView='finger',ukePracticed=false,ukeQuestionIndex=0,ukeQuestionAnswered=false,ukeScoreNodes=[],ukeScoreSegments=[];
let ukeTrack=0;
Learners.mount();
function ukeAvailable(l){return UKE_LESSONS.includes(l)&&MusicTracks.unlocked('ukulele',MusicTracks.of('ukulele',l.id),ukeDone);}
function renderUkePath(){MusicTracks.render(u('ukuleleTracks'),'ukulele',ukeTrack,ukeDone,track=>chooseUkeLesson(MusicTracks.next('ukulele',track,ukeDone)));const trackIds=MusicTracks.list('ukulele',ukeTrack);u('ukeTrackLabel').textContent=MusicTracks.names[ukeTrack]+' track';u('ukeTrackTotal').textContent=trackIds.length;u('ukePath').innerHTML=UKE_UNITS.map((unit,i)=>UKE_LESSONS.some(l=>l.unit===i&&trackIds.includes(l.id))?`<section class="unit-path"><h3>Unit ${i+1} · ${unit.title}<small>${unit.description}</small></h3>${UKE_LESSONS.filter(l=>l.unit===i&&trackIds.includes(l.id)).map(l=>`<button class="path-node ${ukeDone.has(l.id)?'done':''} ${l===ukeCurrent?'current':''}" data-uke-lesson="${l.id}" ${ukeAvailable(l)?'':'disabled'} ${l===ukeCurrent?'aria-current="step"':''}><span class="node-number">${ukeDone.has(l.id)?'✓':ukeAvailable(l)?UKE_LESSONS.indexOf(l)+1:'•'}</span><span><strong>${l.title}</strong><small>${ukeDone.has(l.id)?'Review':l.skill}</small></span></button>`).join('')}</section>`:'').join('');document.querySelectorAll('[data-uke-lesson]').forEach(b=>b.onclick=()=>chooseUkeLesson(b.dataset.ukeLesson));u('ukeCompleted').textContent=MusicTracks.count('ukulele',ukeTrack,ukeDone);u('ukeDaily').textContent=Learners.summary();u('storageWarning').hidden=Learners.storageAvailable;}
function chooseUkeLesson(id){const lesson=UKE_LESSONS.find(l=>l.id===id);if(!lesson||!ukeAvailable(lesson))return;ukeTrack=MusicTracks.of('ukulele',id);stopUke();if(window.speechSynthesis)window.speechSynthesis.cancel();ukeCurrent=lesson;ukeIndex=0;ukePracticed=false;ukeQuestionIndex=0;ukeQuestionAnswered=false;u('ukeReward').hidden=true;u('ukeUnit').textContent=`UNIT ${lesson.unit+1} · ${UKE_UNITS[lesson.unit].title.toUpperCase()}`;u('ukeTitle').textContent=lesson.title;u('ukeSkill').textContent=lesson.skill;const p=Learners.current();u('ukeGuidance').textContent=p.mode==='young'?lesson.young:p.mode==='adult'?lesson.adult:lesson.tip;u('ukeInstructions').innerHTML=lesson.steps.map(s=>`<li>${s}</li>`).join('');u('ukeTip').textContent=lesson.tip;renderUkePath();renderUkeSequence();showUkeNote(lesson.notes[0]);setUkeStage('learn');u('ukeStatus').textContent='Listen once, then play along.';}
function setUkeStage(stage){stopUke();ukeStage=stage;for(const [key,id] of [['learn','ukeLearn'],['practice','ukePractice'],['check','ukeCheck']]){u(id).hidden=stage!==key;const b=u(key+'Step');b.classList.toggle('selected',stage===key);b.setAttribute('aria-pressed',String(stage===key));}if(stage==='practice'){if(ukeView==='sheet')renderUkeScore();showUkeNote(ukeCurrent.notes[ukeIndex]);}if(stage==='check'){if(!ukePracticed){u('ukeQuestion').hidden=false;u('ukeAnswers').hidden=false;u('ukeCheckCount').textContent='PRACTICE FIRST';u('ukeQuestion').textContent='Try the lesson on your instrument first.';u('ukeAnswers').innerHTML='<button class="primary" id="returnPractice">Go to practice →</button>';u('returnPractice').onclick=()=>setUkeStage('practice');u('ukeFeedback').textContent='You decide when you’re ready. We don’t measure your playing.';u('ukeCheckNext').hidden=true;u('ukeReward').hidden=true;}else renderUkeQuestion();}}
function renderUkeSequence(){u('ukeSequence').innerHTML=ukeCurrent.notes.map((n,i)=>`<button data-uke-index="${i}" aria-label="Event ${i+1}: ${ukeName(n)}, ${ukeTab(n)}, ${n.beats} beats">${n.chord?(n.direction==='up'?'↑ ':'↓ '):''}${ukeName(n)}<strong class="tab-label">${ukeTab(n)}</strong><small>${n.beats} beat${n.beats===1?'':'s'}</small></button>`).join('');document.querySelectorAll('[data-uke-index]').forEach(b=>b.onclick=()=>{stopUke();ukeIndex=Number(b.dataset.ukeIndex);showUkeNote(ukeCurrent.notes[ukeIndex]);ensureUkeAudio().then(()=>soundUke(ukeCurrent.notes[ukeIndex]));});}
function drawUkeBoard(n){const voices=ukeVoices(n),xs=ukeFlip?[270,210,150,90]:[90,150,210,270],nut=82,maxFret=Math.max(6,...voices.map(v=>v.fret)),gap=330/maxFret;let svg='<rect x="63" y="80" width="234" height="354" rx="8" fill="#30444b"/><rect x="63" y="77" width="234" height="8" rx="2" fill="#e5d9bf"/>';
 for(let fret=1;fret<=maxFret;fret++){const y=nut+fret*gap;svg+=`<line x1="63" x2="297" y1="${y}" y2="${y}" stroke="#c4d2d5" stroke-width="2"/><text x="45" y="${y-gap/2+4}" text-anchor="middle" font-size="13" fill="#536775">${fret}</text>`;}
 if(n.chord){const barred=voices.filter(v=>v.finger===1);if(barred.length>1&&barred.every(v=>v.fret===barred[0].fret)){const y=nut+(barred[0].fret-.5)*gap;svg+=`<line x1="${Math.min(...barred.map(v=>xs[v.s]))}" x2="${Math.max(...barred.map(v=>xs[v.s]))}" y1="${y}" y2="${y}" stroke="#8156b0" stroke-width="22" stroke-linecap="round"/>`;}}UKE_STRINGS.forEach((s,i)=>{const v=voices.find(v=>v.s===i),active=!!v;svg+=`<text x="${xs[i]}" y="36" text-anchor="middle" font-size="22" font-weight="700" fill="${s.color}">${s.name}</text><line x1="${xs[i]}" x2="${xs[i]}" y1="82" y2="429" stroke="${active?s.color:'#91a4ac'}" stroke-width="${active?4:2}"/>`;if(v){const y=v.fret===0?62:nut+(v.fret-.5)*gap;svg+=`<circle cx="${xs[i]}" cy="${y}" r="20" fill="${s.color}" stroke="white" stroke-width="2"/><text x="${xs[i]}" y="${y+6}" text-anchor="middle" font-size="18" font-weight="700" fill="white">${v.finger}</text>`;}else svg+=`<text x="${xs[i]}" y="65" text-anchor="middle" font-size="20" fill="#71828a">×</text>`;});u('ukeBoard').innerHTML=svg;u('ukeBoard').setAttribute('aria-label',n.rest?'Rest: no playing':voices.map(v=>`${UKE_STRINGS[v.s].name} string, ${v.fret?'fret '+v.fret+', finger '+v.finger:'open'}`).join('; '));}
function showUkeNote(n){drawUkeBoard(n);u('ukeNow').textContent=ukeName(n);u('ukeNowInfo').textContent=n.rest?'No playing · keep counting':n.chord?`${ukeTab(n)} · G C E A`: `${UKE_STRINGS[n.s].name} string · fret ${n.fret}`;u('ukeNowFingers').textContent=n.rest?'':ukeVoices(n).map(v=>`${UKE_STRINGS[v.s].name}: ${v.fret?'finger '+v.finger+' at fret '+v.fret:'open'}`).join(' · ');u('ukeStroke').textContent=n.rest?'Let the silent beat pass.':n.chord?(n.direction==='up'?'↑ Upstroke · A toward G':'↓ Downstroke · G toward A'):'Pluck only the highlighted string.';document.querySelectorAll('[data-uke-index]').forEach(b=>{const active=Number(b.dataset.ukeIndex)===ukeIndex;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});u('ukePrev').disabled=ukeIndex===0;u('ukeNext').disabled=ukeIndex===ukeCurrent.notes.length-1;ukeScoreNodes.forEach(el=>{const active=Number(el.dataset.ukeScoreIndex)===ukeIndex;el.classList.toggle('score-active',active);el.setAttribute('aria-pressed',String(active));});if(ukeView==='sheet'&&ukeStage==='practice'){const el=ukeScoreNodes.find(e=>Number(e.dataset.ukeScoreIndex)===ukeIndex),box=u('ukeScore');if(el){const r=el.getBoundingClientRect(),b=box.getBoundingClientRect();if(r.top<b.top)box.scrollTop+=r.top-b.top-16;else if(r.bottom>b.bottom)box.scrollTop+=r.bottom-b.bottom+16;}}}
async function ensureUkeAudio(){if(!u('ukeSound').checked)return;try{ukeAudio??=new(window.AudioContext||window.webkitAudioContext)();if(ukeAudio.state==='suspended')await ukeAudio.resume();}catch{u('ukeStatus').textContent='Audio is unavailable. The visual practice still works.';}}
function stopUkeAudio(){ukeOscillators.forEach(o=>{try{o.stop();}catch{}});ukeOscillators=[];}
function soundUke(n,duration=.65){stopUkeAudio();if(n.rest||!u('ukeSound').checked||!ukeAudio||ukeAudio.state!=='running')return;let vs=ukeVoices(n);if(n.direction==='up')vs=vs.slice().reverse();vs.forEach((v,i)=>{const o=ukeAudio.createOscillator(),gain=ukeAudio.createGain(),start=ukeAudio.currentTime+(n.chord?i*.025:0),end=start+Math.max(.12,duration);o.type='triangle';o.frequency.value=440*Math.pow(2,(ukePitch(v)-69)/12);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.2/vs.length,start+.012);gain.gain.exponentialRampToValueAtTime(.002,end);o.connect(gain).connect(ukeAudio.destination);o.start(start);o.stop(end);ukeOscillators.push(o);});}
function stopUke(){ukePlaying=false;clearTimeout(ukeTimer);ukeTimer=null;stopUkeAudio();u('ukePlay').textContent='▶ Play along';}
function ukeTick(){if(!ukePlaying)return;const n=ukeCurrent.notes[ukeIndex],duration=n.beats*60/Number(u('ukeTempo').value);showUkeNote(n);soundUke(n,duration*.92);u('ukeStatus').textContent=`${n.rest?'Rest':'Event'} ${ukeIndex+1} of ${ukeCurrent.notes.length} · ${n.beats} beats`;ukeTimer=setTimeout(()=>{if(!ukePlaying)return;if(ukeIndex===ukeCurrent.notes.length-1){if(u('ukeLoop').checked)ukeIndex=0;else{stopUke();u('ukeStatus').textContent='Finished. Repeat a phrase, or take the quick check when you’ve practiced.';return;}}else ukeIndex++;ukeTick();},duration*1000);}
function ukeAbcPitch(v){const midi=ukePitch(v),name=ukeNames[midi%12],oct=Math.floor(midi/12)-1;return(name.includes('♯')?'^':'=')+(oct>=5?name[0].toLowerCase():name[0])+(oct>5?"'".repeat(oct-5):oct<4?','.repeat(4-oct):'');}
function ukeAbcDuration(beats){return beats===1?'':Number.isInteger(beats)?String(beats):Number.isInteger(beats*2)?`${beats*2}/2`:`${beats*4}/4`;}
function buildUkeScore(notes,title,barsPerLine){let abc=`X:1\nT:${title}\nM:4/4\nL:1/4\nK:C clef=treble\n`,beat=0,bar=0,segments=[];notes.forEach((n,sourceIndex)=>{let remaining=n.beats;while(remaining>0){const length=Math.min(remaining,4-beat),tones=ukeVoices(n).map(ukeAbcPitch),symbol=n.rest?'z':n.chord?`[${tones.join('')}]`:tones[0],start=abc.length;if(!n.rest)abc+=`"^${n.chord?ukeName(n)+(n.direction==='up'?' ↑':' ↓'):ukeTab(n)}"`;abc+=symbol+ukeAbcDuration(length);remaining-=length;if(remaining>0&&!n.rest)abc+='-';segments.push({sourceIndex,start,end:abc.length,duration:length});abc+=' ';beat+=length;if(beat===4){abc+='| ';beat=0;bar++;if(bar%barsPerLine===0)abc+='\n';}}});abc=abc.trimEnd();if(beat===0)abc=abc.replace(/\|\s*$/,'');return {abc:abc+'|]',segments};}
function renderUkeScore(){ukeScoreNodes=[];try{if(!window.ABCJS)throw Error('Renderer unavailable');const width=Math.max(280,u('ukeScore').clientWidth||600),built=buildUkeScore(ukeCurrent.notes,ukeCurrent.title,width<520?2:4);ukeScoreSegments=built.segments;window.ABCJS.renderAbc('ukeScore',built.abc,{add_classes:true,responsive:'resize',staffwidth:width-25,paddingtop:12,paddingbottom:20,paddingleft:10,paddingright:10,selectTypes:false,format:{titlefont:'Georgia 20',annotationfont:'Arial 11'}});ukeScoreNodes=Array.from(u('ukeScore').querySelectorAll('.abcjs-note,.abcjs-rest'));ukeScoreNodes.forEach((el,i)=>{const seg=ukeScoreSegments[i];if(!seg)return;el.dataset.ukeScoreIndex=seg.sourceIndex;el.setAttribute('role','button');el.setAttribute('tabindex','0');const n=ukeCurrent.notes[seg.sourceIndex];el.setAttribute('aria-label',`Event ${seg.sourceIndex+1}: ${ukeName(n)}, ${ukeTab(n)}`);const seek=()=>{stopUke();ukeIndex=seg.sourceIndex;showUkeNote(ukeCurrent.notes[ukeIndex]);ensureUkeAudio().then(()=>soundUke(ukeCurrent.notes[ukeIndex]));};el.addEventListener('click',seek);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();seek();}});});u('ukeScoreTitle').textContent=ukeCurrent.title;u('ukeScoreError').hidden=true;}catch{u('ukeScore').textContent='';u('ukeScoreError').hidden=false;u('ukeScoreError').textContent='The score could not load. Finger view and playback still work.';}}
function setUkeView(view){ukeView=view;u('ukeFingerStage').hidden=view!=='finger';u('ukeSheetStage').hidden=view!=='sheet';for(const key of ['finger','sheet']){u('uke'+(key==='finger'?'Finger':'Sheet')+'View').classList.toggle('selected',view===key);u('uke'+(key==='finger'?'Finger':'Sheet')+'View').setAttribute('aria-pressed',String(view===key));}if(view==='sheet')renderUkeScore();showUkeNote(ukeCurrent.notes[ukeIndex]);}
function shuffleUke(items){const a=items.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function renderUkeQuestion(){if(ukeQuestionIndex>=ukeCurrent.checks.length){finishUkeLesson();return;}ukeQuestionAnswered=false;const q=ukeCurrent.checks[ukeQuestionIndex];u('ukeReward').hidden=true;u('ukeQuestion').hidden=false;u('ukeAnswers').hidden=false;u('ukeCheckCount').textContent=`QUESTION ${ukeQuestionIndex+1} OF ${ukeCurrent.checks.length}`;u('ukeQuestion').textContent=q.prompt;u('ukeFeedback').textContent='';u('ukeCheckNext').hidden=true;u('ukeAnswers').innerHTML=shuffleUke(q.options.map((text,i)=>({text,i}))).map(o=>`<button data-uke-answer="${o.i}">${o.text}</button>`).join('');document.querySelectorAll('[data-uke-answer]').forEach(b=>b.onclick=()=>{if(ukeQuestionAnswered)return;const correct=Number(b.dataset.ukeAnswer)===q.answer;if(correct){ukeQuestionAnswered=true;b.classList.add('correct');u('ukeFeedback').textContent='That’s right. '+q.explanation;u('ukeCheckNext').hidden=false;u('ukeCheckNext').textContent=ukeQuestionIndex===ukeCurrent.checks.length-1?'Finish lesson →':'Next question →';document.querySelectorAll('[data-uke-answer]').forEach(x=>x.disabled=true);}else{b.classList.add('incorrect');b.disabled=true;u('ukeFeedback').textContent='Try again. '+q.explanation;}});}
function finishUkeLesson(){stopUke();const rewarded=Learners.complete('ukulele',ukeCurrent.id);ukeDone.add(ukeCurrent.id);renderUkePath();u('ukeQuestion').hidden=true;u('ukeAnswers').hidden=true;u('ukeCheckNext').hidden=true;u('ukeFeedback').textContent='';u('ukeCheckCount').textContent='LESSON COMPLETE';u('ukeReward').hidden=false;const candidate=UKE_LESSONS[UKE_LESSONS.indexOf(ukeCurrent)+1],next=candidate&&ukeAvailable(candidate)?candidate:null,trackFinished=MusicTracks.complete('ukulele',ukeTrack,ukeDone);u('ukeReward').innerHTML=`<h3>${rewarded?'A small step, well played.':'Good review.'}</h3><p><strong>${rewarded?'+20 XP':'Already practiced · progress kept'}</strong></p><p>${MusicTracks.count('ukulele',ukeTrack,ukeDone)} of ${MusicTracks.list('ukulele',ukeTrack).length} ${MusicTracks.names[ukeTrack].toLowerCase()} lessons complete. ${trackFinished?(ukeTrack<2?MusicTracks.names[ukeTrack+1]+' is now open.':'All tracks complete. Revisit your favorites.'):'Keep practicing this track in any order.'} ${next?'Your next step is '+next.title+'.':''}</p><button class="primary" id="nextUkeLesson">${next?'Next lesson →':'Choose another lesson'}</button><button id="reviewUkeLesson">Practice again</button>`;u('nextUkeLesson').onclick=()=>chooseUkeLesson(next?next.id:MusicTracks.next('ukulele',ukeTrack,ukeDone));u('reviewUkeLesson').onclick=()=>setUkeStage('practice');}
u('learnStep').onclick=()=>setUkeStage('learn');u('practiceStep').onclick=()=>setUkeStage('practice');u('checkStep').onclick=()=>setUkeStage('check');u('startUkePractice').onclick=()=>setUkeStage('practice');u('finishUkePractice').onclick=()=>{ukePracticed=true;ukeQuestionIndex=0;setUkeStage('check');};u('ukeCheckNext').onclick=()=>{ukeQuestionIndex++;renderUkeQuestion();};u('ukeFingerView').onclick=()=>setUkeView('finger');u('ukeSheetView').onclick=()=>setUkeView('sheet');u('ukeFlip').onclick=()=>{ukeFlip=!ukeFlip;u('ukeFlip').setAttribute('aria-pressed',String(ukeFlip));drawUkeBoard(ukeCurrent.notes[ukeIndex]);};
u('ukePlay').onclick=async()=>{if(ukePlaying){stopUke();return;}await ensureUkeAudio();if(ukeIndex===ukeCurrent.notes.length-1)ukeIndex=0;ukePlaying=true;u('ukePlay').textContent='Ⅱ Pause';ukeTick();};u('ukePrev').onclick=()=>{stopUke();ukeIndex=Math.max(0,ukeIndex-1);showUkeNote(ukeCurrent.notes[ukeIndex]);};u('ukeNext').onclick=()=>{stopUke();ukeIndex=Math.min(ukeCurrent.notes.length-1,ukeIndex+1);showUkeNote(ukeCurrent.notes[ukeIndex]);};u('ukeRestart').onclick=()=>{stopUke();ukeIndex=0;showUkeNote(ukeCurrent.notes[0]);};u('ukeTempo').oninput=()=>{u('ukeTempoValue').textContent=u('ukeTempo').value+' BPM';if(ukePlaying){clearTimeout(ukeTimer);ukeTick();}};u('ukeSound').onchange=()=>u('ukeSound').checked?ensureUkeAudio():stopUkeAudio();
if(!window.speechSynthesis)u('ukeSpeak').hidden=true;else u('ukeSpeak').onclick=()=>{window.speechSynthesis.cancel();const p=Learners.current(),text=[ukeCurrent.title,p.mode==='young'?ukeCurrent.young:p.mode==='adult'?ukeCurrent.adult:ukeCurrent.tip,...ukeCurrent.steps].join('. ');const speech=new SpeechSynthesisUtterance(text);speech.rate=p.mode==='young'?.85:1;window.speechSynthesis.speak(speech);};
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopUke();if(window.speechSynthesis)window.speechSynthesis.cancel();}});let ukeResizeTimer;window.addEventListener('resize',()=>{clearTimeout(ukeResizeTimer);ukeResizeTimer=setTimeout(()=>{if(ukeView==='sheet'&&ukeStage==='practice'){renderUkeScore();showUkeNote(ukeCurrent.notes[ukeIndex]);}},150);});
if(!ukeAvailable(ukeCurrent))ukeCurrent=UKE_LESSONS[0];
chooseUkeLesson(ukeCurrent.id);
