const fs=require('fs'),assert=require('assert'),{JSDOM,VirtualConsole}=require('jsdom');const root=require('path').join(__dirname,'../');
const saved=new Map(),vc=new VirtualConsole();vc.on('error',console.error);const dom=new JSDOM(fs.readFileSync(root+'ensemble.html','utf8'),{url:'https://example.com/ensemble.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;Object.defineProperty(w,'localStorage',{value:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)}});w.matchMedia=()=>({matches:true});w.HTMLDialogElement.prototype.showModal=function(){};w.eval(fs.readFileSync(root+'learners.js','utf8'));w.eval(fs.readFileSync(root+'vendor/abcjs-basic-min.js','utf8'));w.eval(fs.readFileSync(root+'ensemble-data.js','utf8')+'\n'+fs.readFileSync(root+'istanbul-data.js','utf8')+'\n'+fs.readFileSync(root+'ensemble.js','utf8')+'\nwindow.enTest={songs:ENSEMBLE_SONGS,build:buildEnsemble,score:buildEnsembleScore,choose:chooseEnsemble,seek:seekEnsemble,pitches:ensemblePitches,enabled:ensembleEnabled,getIndex:()=>ensembleIndex};');const t=w.enTest;
assert.equal(t.songs.length,10);for(const i of ['violin','ukulele','accordion'])assert(t.songs.filter(s=>s.lead===i).length>=3);
for(const song of t.songs){t.choose(song.id);const steps=t.build(song),beats=Number(song.meter.split('/')[0]);const duration=steps.reduce((sum,n)=>sum+n.beats,0);assert.equal(duration,song.melody.reduce((sum,n)=>sum+n.beats,0));assert.equal(duration%beats,0);assert.equal(song.harmony.length,duration/beats,song.title+' chord bars');assert(w.document.querySelector('#ensembleScoreError').hidden,song.title+' score');const built=t.score(song,steps);const parsed=w.ABCJS.parseOnly(built.abc)[0],voiceDurations=[0,0,0,0];for(const line of parsed.lines)for(let si=0;si<(line.staff||[]).length;si++)for(const voice of line.staff[si].voices||[])for(const event of voice)if(event.el_type==='note')voiceDurations[si]+=event.duration*4;assert.deepEqual(voiceDurations,[duration,duration,duration,duration],song.title+' synchronized voices');
 assert.equal(w.document.querySelectorAll('#ensembleScore [data-ensemble-beat]').length,steps.length*4,song.title+' mapped score');
 for(const step of steps){for(const i of ['violin','ukulele','accordion']){const part=step.parts[i];if(i==='violin'&&!part.rest){assert(part.semi>=0&&part.semi<=7);assert(part.finger>=0&&part.finger<=4);}if(i==='ukulele'&&!part.chord&&!part.rest){assert(part.fret>=0&&part.fret<=3);assert(part.finger>=0&&part.finger<=3);}if(i==='accordion'){assert([58,60,62,64,65,67].includes(part.midi));assert(part.finger>=1&&part.finger<=5);if(part.left)assert(['Bb','C','F','G'].includes(part.left.root));}assert(t.pitches(part,i).every(p=>p>=48&&p<=79));}}
 for(const i of ['violin','ukulele','accordion']){w.document.querySelector('[data-ensemble-part="'+i+'"]').click();assert(w.document.querySelector('#ensembleDiagram svg'));}t.seek(3);assert.equal(w.document.querySelectorAll('#ensembleScore .ensemble-active').length,4);assert.equal(t.getIndex(),3);assert.equal(w.Learners.current().progress.ensemble.length,0);assert.equal(w.Learners.current().xp,0);
}
w.document.querySelector('[data-ensemble-solo="ukulele"]').click();assert.equal(t.enabled.ukulele,true);assert.equal(t.enabled.violin,false);assert.equal(t.enabled.accordion,false);w.document.querySelector('#ensembleAll').click();assert(Object.values(t.enabled).every(Boolean));w.document.querySelector('#ensembleComplete').click();assert.equal(w.Learners.current().xp,20);assert.equal(w.Learners.current().progress.ensemble.length,1);assert.equal(w.Learners.current().progress.violin.length,0);assert.equal(w.Learners.current().progress.ukulele.length,0);assert.equal(w.Learners.current().progress.accordion.length,0);w.document.querySelector('#ensembleComplete').click();assert.equal(w.Learners.current().xp,20);
const istanbul=t.songs.find(s=>s.id==='ens-istanbul');assert.equal(istanbul.harmony.length,48);assert.equal(istanbul.key,'Cm');assert(istanbul.melody.some(n=>n.rest));assert(istanbul.melody.some(n=>n.beats<.5));assert.equal(istanbul.lead,'violin');
console.log('PASS: ten trio arrangements, three leads per instrument, synchronized four-staff durations, score seeking/highlighting, playable ranges, three finger diagrams, mixer solo/full trio, and isolated ensemble progress.');dom.window.close();
