const fs=require('fs'),assert=require('assert');const {JSDOM,VirtualConsole}=require('jsdom');const root=require('path').join(__dirname,'../');
const saved=new Map([['little-strings-progress',JSON.stringify(['open','bow'])]]);
function setup(page){const vc=new VirtualConsole();const dom=new JSDOM(fs.readFileSync(root+page,'utf8'),{url:'https://example.com/'+page,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;Object.defineProperty(w,'localStorage',{value:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)}});w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(fs.readFileSync(root+'learners.js','utf8'));return {dom,w};}
const {dom,w}=setup('ukulele.html');assert.deepEqual(Array.from(w.Learners.current().progress.violin),['open','bow']);w.eval(fs.readFileSync(root+'vendor/abcjs-basic-min.js','utf8'));w.eval(fs.readFileSync(root+'uke-data.js','utf8')+'\n'+fs.readFileSync(root+'ukulele.js','utf8')+'\nwindow.ukeTest={lessons:UKE_LESSONS,strings:UKE_STRINGS,chords:UKE_CHORDS,pitch:ukePitch,voices:ukeVoices,build:buildUkeScore,choose:chooseUkeLesson,stage:setUkeStage,view:setUkeView,done:()=>[...ukeDone]};');
const t=w.ukeTest;assert.equal(t.lessons.length,18);assert.deepEqual(t.strings.map(x=>x.midi),[67,60,64,69]);
assert(w.document.querySelector('[data-uke-lesson="tune"]').disabled);t.stage('check');assert.equal(w.document.querySelector('#ukeCheckCount').textContent,'PRACTICE FIRST');assert.equal(w.Learners.current().progress.ukulele.length,0);
for(const lesson of t.lessons){
 t.choose(lesson.id);assert.equal(w.document.querySelector('#ukeTitle').textContent,lesson.title);t.stage('practice');t.view('sheet');assert(w.document.querySelector('#ukeScoreError').hidden,lesson.id+' score error');
 const built=t.build(lesson.notes,lesson.title,4);assert.equal(w.document.querySelectorAll('#ukeScore .abcjs-note,#ukeScore .abcjs-rest').length,built.segments.length,lesson.id+' rendered event mapping');
 const parsed=w.ABCJS.parseOnly(built.abc)[0];let beats=0;for(const line of parsed.lines)for(const staff of line.staff||[])for(const voice of staff.voices||[])for(const e of voice)if(e.el_type==='note')beats+=e.duration*4;assert.equal(beats,lesson.notes.reduce((sum,n)=>sum+n.beats,0),lesson.id+' duration');
 for(const n of lesson.notes)for(const v of t.voices(n)){assert(v.s>=0&&v.s<=3);assert(v.fret>=0&&v.fret<=6);assert(v.finger>=0&&v.finger<=4);}
 w.document.querySelector('#finishUkePractice').click();
 for(const q of lesson.checks){const bad=w.document.querySelector('[data-uke-answer="'+((q.answer+1)%q.options.length)+'"]');bad.click();assert(w.document.querySelector('#ukeFeedback').textContent.includes('Try again'));assert(w.document.querySelector('#ukeCheckNext').hidden);w.document.querySelector('[data-uke-answer="'+q.answer+'"]').click();assert(!w.document.querySelector('#ukeCheckNext').hidden);w.document.querySelector('#ukeCheckNext').click();}
 assert(w.Learners.current().progress.ukulele.includes(lesson.id));
}
assert.equal(w.Learners.current().xp,360);assert.equal(t.done().length,18);assert.equal(w.Learners.streak(),1);assert.equal(w.Learners.current().days[w.Learners.today()],18);assert.equal(w.Learners.complete('ukulele','hold'),false);assert.equal(w.Learners.current().xp,360);
for(const [name,chord] of Object.entries(t.chords)){const pcs=t.voices({chord:name}).map(v=>t.pitch(v)%12);const expected={C:[0,4,7],Am:[0,4,9],F:[0,5,9],G7:[2,5,7,11],G:[2,7,11]}[name];assert.deepEqual([...new Set(pcs)].sort((a,b)=>a-b),expected,name+' chord pitches');}
t.choose('chord-c');t.stage('practice');t.view('finger');const marker=Array.from(w.document.querySelectorAll('#ukeBoard circle')).find(el=>el.getAttribute('cy')==='219.5');assert(marker,'C marker behind fret 3');
w.document.querySelector('#learnerOpen').click();w.document.querySelector('#learnerName').value='New learner <b>';w.document.querySelector('#learnerMode').value='young';w.document.querySelector('#learnerGoal').value='2';w.document.querySelector('#learnerForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(w.Learners.current().name,'New learner <b>');assert.equal(w.Learners.current().progress.ukulele.length,0);assert.equal(w.Learners.current().progress.violin.length,0);assert.equal(JSON.parse(saved.get('little-strings-learners-v1')).profiles[0].progress.ukulele.length,18);
const second=setup('violin.html');assert.equal(second.w.Learners.current().mode,'young');second.w.Learners.mount();assert(!second.w.document.querySelector('#learnerOpen b'),'nickname escaped');second.w.eval(fs.readFileSync(root+'vendor/abcjs-basic-min.js','utf8'));second.w.eval(fs.readFileSync(root+'sherlock.js','utf8')+'\n'+fs.readFileSync(root+'app.js','utf8')+'\nwindow.violinTest={choose:selectLesson,count:lessons.length,progress:()=>[...completed]};');assert.equal(second.w.violinTest.count,16);assert.equal(second.w.violinTest.progress().length,0);second.w.violinTest.choose('first');second.w.document.querySelector('#complete').click();assert.deepEqual(Array.from(second.w.Learners.current().progress.violin),['first']);assert.equal(second.w.Learners.current().xp,20);assert.equal(second.w.Learners.current().progress.ukulele.length,0);
second.w.document.querySelector('#complete').click();assert.equal(second.w.Learners.current().progress.violin.length,0);assert.equal(JSON.parse(saved.get('little-strings-learners-v1')).profiles[0].progress.violin.length,2);second.w.document.querySelector('#complete').click();assert.equal(second.w.Learners.current().xp,20);second.w.violinTest.choose('221b');second.w.document.querySelector('#sheetView').click();assert.equal(second.w.document.querySelectorAll('#fullScore .abcjs-note,#fullScore .abcjs-rest').length,146);assert(second.w.document.querySelector('#complete').hidden);
console.log('PASS: 18 ukulele lessons render; score/timing mappings; chord pitches; fret placement; practice/check gating and retry; sequential unlocks; XP/streaks; two-profile isolation; legacy progress migration; violin completion/undo isolation; hidden 221B score preserved.');dom.window.close();second.dom.window.close();
