const fs=require('fs'),assert=require('assert');const {JSDOM,VirtualConsole}=require('jsdom');const root=require('path').join(__dirname,'../');
const saved=new Map([['little-strings-progress',JSON.stringify(['open','bow'])]]);
function setup(page){const vc=new VirtualConsole();const dom=new JSDOM(fs.readFileSync(root+page,'utf8'),{url:'https://example.com/'+page,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;Object.defineProperty(w,'localStorage',{value:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)}});w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(fs.readFileSync(root+'tracks.js','utf8'));w.eval(fs.readFileSync(root+'learners.js','utf8'));return {dom,w};}
const {dom,w}=setup('ukulele.html');assert.deepEqual(Array.from(w.Learners.current().progress.violin),['open','bow']);w.eval(fs.readFileSync(root+'vendor/abcjs-basic-min.js','utf8'));w.eval(fs.readFileSync(root+'uke-data.js','utf8')+'\n'+fs.readFileSync(root+'formby-data.js','utf8')+'\n'+fs.readFileSync(root+'ukulele.js','utf8')+'\n'+fs.readFileSync(root+'formby.js','utf8')+'\nwindow.ukeTest={lessons:UKE_LESSONS,strings:UKE_STRINGS,chords:UKE_CHORDS,pitch:ukePitch,voices:ukeVoices,build:buildUkeScore,choose:chooseUkeLesson,stage:setUkeStage,view:setUkeView,done:()=>[...ukeDone]};');
const t=w.ukeTest;assert.equal(t.lessons.length,30);assert.deepEqual(t.strings.map(x=>x.midi),[67,60,64,69]);
assert.equal(w.document.querySelectorAll('[data-uke-lesson]').length,18);assert(!w.document.querySelector('[data-uke-lesson="syncopation"]'));assert(!w.document.querySelector('[data-track="1"]').disabled);assert(!w.document.querySelector('[data-track="2"]').disabled);
t.choose('uke-capstone');assert.equal(w.document.querySelector('#ukeTitle').textContent,t.lessons[29].title);assert.equal(w.Learners.current().progress.ukulele.length,0);assert.equal(w.Learners.current().xp,0);w.document.querySelector('[data-track="0"]').click();w.document.querySelector('[data-uke-lesson="first-piece"]').click();assert.equal(w.document.querySelector('#ukeTitle').textContent,t.lessons[17].title);assert.equal(w.Learners.current().progress.ukulele.length,0);
w.document.querySelector('[data-uke-lesson="hold"]').click();assert.equal(w.document.querySelector('#ukeTitle').textContent,t.lessons[0].title);t.stage('check');assert.equal(w.document.querySelector('#ukeCheckCount').textContent,'PRACTICE FIRST');assert.equal(w.Learners.current().progress.ukulele.length,0);
for(const lesson of t.lessons){
 t.choose(lesson.id);assert.equal(w.document.querySelector('#ukeTitle').textContent,lesson.title);t.stage('practice');t.view('sheet');assert(w.document.querySelector('#ukeScoreError').hidden,lesson.id+' score error');
 const built=t.build(lesson.notes,lesson.title,4,lesson);assert.equal(w.document.querySelectorAll('#ukeScore .abcjs-note,#ukeScore .abcjs-rest').length,built.segments.length,lesson.id+' rendered event mapping');
 const parsed=w.ABCJS.parseOnly(built.abc)[0];let beats=0;for(const line of parsed.lines)for(const staff of line.staff||[])for(const voice of staff.voices||[])for(const e of voice)if(e.el_type==='note')beats+=e.duration*4;assert.equal(beats,lesson.notes.reduce((sum,n)=>sum+n.beats,0),lesson.id+' duration');
 for(const n of lesson.notes)for(const v of t.voices(n)){assert(v.s>=0&&v.s<=3);assert(v.fret>=0&&v.fret<=12);assert(v.finger>=0&&v.finger<=4);}
 w.document.querySelector('#finishUkePractice').click();
 for(const q of lesson.checks){const bad=w.document.querySelector('[data-uke-answer="'+((q.answer+1)%q.options.length)+'"]');bad.click();assert(w.document.querySelector('#ukeFeedback').textContent.includes('Try again'));assert(w.document.querySelector('#ukeCheckNext').hidden);w.document.querySelector('[data-uke-answer="'+q.answer+'"]').click();assert(!w.document.querySelector('#ukeCheckNext').hidden);w.document.querySelector('#ukeCheckNext').click();}
 assert(w.Learners.current().progress.ukulele.includes(lesson.id));if(lesson.id==='first-piece'){assert(!w.document.querySelector('[data-track="1"]').disabled);assert(!w.document.querySelector('[data-track="2"]').disabled);assert.equal(w.document.querySelector('#ukeCompleted').textContent,'18');}if(lesson.id==='minor-piece')assert(!w.document.querySelector('[data-track="2"]').disabled);
}
assert.equal(w.Learners.current().xp,600);assert.equal(t.done().length,30);assert.equal(w.Learners.streak(),1);assert.equal(w.Learners.current().days[w.Learners.today()],30);assert.equal(w.Learners.complete('ukulele','hold'),false);assert.equal(w.Learners.current().xp,600);
for(const [name,chord] of Object.entries(t.chords)){const pcs=t.voices({chord:name}).map(v=>t.pitch(v)%12);const expected={C:[0,4,7],Am:[0,4,9],F:[0,5,9],G7:[2,5,7,11],G:[2,7,11],Dm:[2,5,9],E7:[2,4,8,11],Bb:[2,5,10],'C-high':[0,4,7],'D-high':[2,6,9],Cmaj7:[0,4,7,11],Am7:[0,4,7,9]}[name];assert.deepEqual([...new Set(pcs)].sort((a,b)=>a-b),expected,name+' chord pitches');}
t.choose('chord-c');t.stage('practice');t.view('finger');const marker=Array.from(w.document.querySelectorAll('#ukeBoard circle')).find(el=>el.getAttribute('cy')==='219.5');assert(marker,'C marker behind fret 3');
w.document.querySelector('#learnerOpen').click();w.document.querySelector('#learnerName').value='New learner <b>';w.document.querySelector('#learnerMode').value='young';w.document.querySelector('#learnerGoal').value='2';w.document.querySelector('#learnerForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(w.Learners.current().name,'New learner <b>');assert.equal(w.Learners.current().progress.ukulele.length,0);assert.equal(w.Learners.current().progress.violin.length,0);assert.equal(JSON.parse(saved.get('little-strings-learners-v1')).profiles[0].progress.ukulele.length,30);
const second=setup('violin.html');assert.equal(second.w.Learners.current().mode,'young');second.w.Learners.mount();assert(!second.w.document.querySelector('#learnerOpen b'),'nickname escaped');second.w.eval(fs.readFileSync(root+'vendor/abcjs-basic-min.js','utf8'));second.w.eval(fs.readFileSync(root+'sherlock.js','utf8')+'\n'+fs.readFileSync(root+'noble.js','utf8')+'\n'+fs.readFileSync(root+'app.js','utf8')+'\nwindow.violinTest={choose:selectLesson,count:lessons.length,lessons,voices,pattern,build:buildScore,progress:()=>[...completed]};');assert.equal(second.w.violinTest.count,29);assert.equal(second.w.violinTest.progress().length,0);second.w.violinTest.choose('first');second.w.document.querySelector('#complete').click();assert.deepEqual(Array.from(second.w.Learners.current().progress.violin),['first']);assert.equal(second.w.Learners.current().xp,20);assert.equal(second.w.Learners.current().progress.ukulele.length,0);
second.w.document.querySelector('#complete').click();assert.equal(second.w.Learners.current().progress.violin.length,0);assert.equal(JSON.parse(saved.get('little-strings-learners-v1')).profiles[0].progress.violin.length,2);second.w.document.querySelector('#complete').click();assert.equal(second.w.Learners.current().xp,20);assert.equal(second.w.document.querySelectorAll('[data-lesson]').length,16);assert(!second.w.document.querySelector('[data-track="1"]').disabled);second.w.violinTest.choose('violin-capstone');assert.equal(second.w.document.querySelector('#lessonTitle').textContent,second.w.violinTest.lessons.find(l=>l.id==='violin-capstone').title);assert.deepEqual(Array.from(second.w.violinTest.progress()),['first']);for(const lesson of second.w.violinTest.lessons){second.w.violinTest.choose(lesson.id);second.w.document.querySelector('#sheetView').click();assert(second.w.document.querySelector('#scoreError').hidden,lesson.id+' violin score');const built=second.w.violinTest.build(lesson.notes,lesson.title,4,lesson);assert.equal(second.w.document.querySelectorAll('#fullScore .abcjs-note,#fullScore .abcjs-rest').length,built.segments.length,lesson.id+' violin mapping');let beats=0;for(const line of second.w.ABCJS.parseOnly(built.abc)[0].lines)for(const staff of line.staff||[])for(const voice of staff.voices||[])for(const e of voice)if(e.el_type==='note')beats+=e.duration*4;assert.equal(beats,lesson.notes.reduce((a,n)=>a+n.beats,0),lesson.id+' violin duration');for(const n of lesson.notes){for(const v of second.w.violinTest.voices(n)){const pat=second.w.violinTest.pattern(v);assert(pat&&pat.finger>=0&&pat.finger<=4);}}for(const circle of second.w.document.querySelectorAll('#fingerboard .marker'))assert(Number(circle.getAttribute('cy'))<=437,lesson.id+' marker within board');if(!second.w.violinTest.progress().includes(lesson.id))second.w.document.querySelector('#complete').click();if(lesson.id==='arpeggio'){assert(!second.w.document.querySelector('[data-track="1"]').disabled);assert(!second.w.document.querySelector('[data-track="2"]').disabled);assert.equal(second.w.document.querySelector('#completedCount').textContent,'16');}if(lesson.id==='third-piece')assert(!second.w.document.querySelector('[data-track="2"]').disabled);if(lesson.id==='noble-maiden-fair'){assert(!second.w.document.querySelector('[data-track="2"]').disabled);assert.equal(lesson.notes.reduce((a,n)=>a+n.beats,0),99);assert(built.abc.includes('M:3/4'));assert(built.abc.includes('K:G'));assert.equal(built.segments.length,lesson.notes.length);assert.equal(lesson.notes.filter(n=>n.rest).length,2);assert.equal(lesson.notes.filter(n=>n.tie).length,12);}}
second.w.violinTest.choose('221b');second.w.document.querySelector('#sheetView').click();assert.equal(second.w.document.querySelectorAll('#fullScore .abcjs-note,#fullScore .abcjs-rest').length,146);assert(second.w.document.querySelector('#complete').hidden);

// Ten logo clicks, never three or nine; secret access must not award progress.
second.w.violinTest.choose('open');const beforeSecret=second.w.Learners.current().xp;
for(let i=0;i<9;i++)second.w.document.querySelector('.brand').click();assert.equal(second.w.document.querySelector('#lessonTitle').textContent,'Hello, four strings');second.w.document.querySelector('.brand').click();assert(second.w.document.querySelector('#complete').hidden);assert.equal(second.w.Learners.current().xp,beforeSecret);
// Four ukulele clicks reveal six song choices, whose drills leave normal progress untouched.
const beforeFormby=w.Learners.current().xp;for(let i=0;i<3;i++)w.document.querySelector('.brand').click();assert(w.document.querySelector('#formbyRoom').hidden);w.document.querySelector('.brand').click();assert(!w.document.querySelector('#formbyRoom').hidden);assert.equal(w.document.querySelectorAll('[data-formby]').length,6);
for(const button of w.document.querySelectorAll('[data-formby]')){button.click();t.view('sheet');assert(w.document.querySelector('#ukeScoreError').hidden);assert(w.document.querySelector('#checkStep').disabled);w.document.querySelector('#finishUkePractice').click();}assert.equal(w.Learners.current().xp,beforeFormby);assert.equal(w.Learners.current().progress.ukulele.length,0);w.document.querySelector('#closeFormby').click();assert(!w.document.querySelector('#checkStep').disabled);
const accordion=setup('accordion.html');const aw=accordion.w;assert.equal(aw.Learners.current().progress.accordion.length,0);aw.eval(fs.readFileSync(root+'vendor/abcjs-basic-min.js','utf8'));aw.eval(fs.readFileSync(root+'accordion-data.js','utf8')+'\n'+fs.readFileSync(root+'accordion.js','utf8')+'\nwindow.accTest={lessons:ACC_LESSONS,choose:chooseAccLesson,stage:setAccStage,view:setAccView,build:buildAccScore,left:accLeftPitches};');const at=aw.accTest;assert.equal(at.lessons.length,16);
at.choose('acc-finale');assert.equal(aw.Learners.current().progress.accordion.length,0);at.stage('check');assert(aw.document.querySelector('#accGoPractice'));assert.equal(aw.Learners.current().progress.accordion.length,0);at.stage('practice');aw.document.querySelector('#accFinishPractice').click();aw.document.querySelector('[data-acc-answer="0"]').click();assert.deepEqual(Array.from(aw.Learners.current().progress.accordion),['acc-finale']);
for(const lesson of at.lessons){at.choose(lesson.id);at.stage('practice');at.view('sheet');assert(aw.document.querySelector('#accScoreError').hidden,lesson.id+' accordion score');const built=at.build(lesson);assert.equal(aw.document.querySelectorAll('#accScore .abcjs-note,#accScore .abcjs-rest').length,built.segments.length*2,lesson.id+' two-hand score mapping');assert.equal(aw.document.querySelectorAll('[data-acc-score-index]').length,built.segments.length*2,lesson.id+' clickable score nodes');let voiceBeats=[0,0];for(const line of aw.ABCJS.parseOnly(built.abc)[0].lines)for(let i=0;i<(line.staff||[]).length;i++)for(const voice of line.staff[i].voices||[])for(const event of voice)if(event.el_type==='note')voiceBeats[i]+=event.duration*4;assert.deepEqual(voiceBeats,[lesson.notes.reduce((v,n)=>v+n.beats,0),lesson.notes.reduce((v,n)=>v+n.beats,0)],lesson.id+' both hands timing');
for(const n of lesson.notes){if(n.midi!=null){assert(n.midi>=53&&n.midi<=93);assert(n.finger>=1&&n.finger<=5);}if(n.left){assert(['C','F','G'].includes(n.left.root));assert(n.left.finger>=1&&n.left.finger<=5);}}
at.view('finger');assert.equal(aw.document.querySelectorAll('#accFullKeys [data-key]').length,41);assert.equal(aw.document.querySelectorAll('#accFullBass [data-bass]').length,120);aw.document.querySelector('#accFinishPractice').click();aw.document.querySelector('[data-acc-answer="'+((lesson.check.answer+1)%lesson.check.options.length)+'"]').click();assert(aw.document.querySelector('#accFeedback').textContent.includes('Try again'));aw.document.querySelector('[data-acc-answer="'+lesson.check.answer+'"]').click();assert(aw.Learners.current().progress.accordion.includes(lesson.id));}
assert.equal(aw.Learners.current().progress.accordion.length,16);assert.equal(aw.Learners.current().progress.ukulele.length,0);assert.equal(JSON.parse(saved.get('little-strings-learners-v1')).profiles[0].progress.accordion.length,0);accordion.dom.window.close();
/* tests below */
console.log('PASS: 30 ukulele lessons render; score/timing mappings; chord pitches; fret placement; practice/check gating and retry; free navigation within tracks; open tracks without implied completion; XP/streaks; two-profile isolation; legacy progress migration; all 29 violin scores and markers; violin completion/undo isolation; hidden 221B score preserved; exact 10/4-click secret triggers; six Formby drills; all 16 accordion scores, contacts, and isolated completions.');dom.window.close();second.dom.window.close();
